from __future__ import annotations

import argparse
import datetime as dt
import os
import sqlite3


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "components.db")


SEED_ROWS = [
    {
        "品牌": "KEMET",
        "型号": "R82DC3100AA50J",
        "系列": "R82",
        "系列说明": "Metallized polyester stacked film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "63",
        "特殊用途": "Automotive grade DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.2x2.5x6.5",
        "长度（mm）": "7.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET 薄膜电容 0.1uF ±5% 63VDC 径向 P=5.0mm 7.2x2.5x6.5mm",
        "生产状态": "Active",
        "工作温度": "-55~105℃",
        "官网链接": "https://search.kemet.com/component-documentation/download/specsheet/R82DC3100AA50J",
        "数据来源": "KEMET/YAGEO official spec sheet",
        "数据状态": "官方PDF",
        "校验备注": "R82DC3100AA50J: 0.1uF, 5%, 63VDC, metallized polyester, radial, P=5mm",
    },
    {
        "品牌": "WIMA",
        "型号": "MKS2C031001A00JSSD",
        "系列": "MKS2",
        "系列说明": "Metallized polyester film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "63",
        "特殊用途": "General DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.2x2.5x6.5",
        "长度（mm）": "7.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET 薄膜电容 0.1uF ±5% 63VDC WIMA MKS2 P=5.0mm",
        "生产状态": "Active",
        "工作温度": "-55~125℃",
        "官网链接": "https://www.wima.de/wp-content/uploads/media/e_WIMA_MKS_2.pdf",
        "数据来源": "WIMA official MKS2 datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MKS2C031001A00JSSD: 0.1uF row, 63VDC, J=5%, bulk S, pin length SD",
    },
    {
        "品牌": "Panasonic",
        "型号": "ECWFD2W105J",
        "系列": "ECWFD",
        "系列说明": "Metallized PP film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "450",
        "特殊用途": "Resin dipped radial leaded DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P15.0",
        "尺寸（mm）": "17.5x7.8x11.0",
        "长度（mm）": "17.5",
        "宽度（mm）": "7.8",
        "高度（mm）": "11.0",
        "脚距（mm）": "15.0",
        "规格摘要": "PP 薄膜电容 1uF ±5% 450VDC 径向 P=15.0mm",
        "生产状态": "Active",
        "工作温度": "-40~110℃",
        "官网链接": "https://industrial.panasonic.com/ww/products/pt/film-cap-electroequip/models/ECWFD2W105J",
        "数据来源": "Panasonic official product page",
        "数据状态": "官方网页",
        "校验备注": "ECWFD2W105J: 1uF, ±5%, 450VDC, MPP, L=17.5 T=7.8 H=11.0, P=15.0",
    },
    {
        "品牌": "TDK",
        "型号": "B32529C0104K000",
        "系列": "B32529",
        "系列说明": "MKT general purpose film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "63",
        "特殊用途": "RFI filtering / smoothing / general purpose",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.3x2.5x6.5",
        "长度（mm）": "7.3",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET/MKT 薄膜电容 0.1uF ±10% 63VDC TDK B32529 P=5.0mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/en/search/capacitor/film/rfi_general/info?part_no=B32529C0104K000",
        "数据来源": "TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "B32529C0104K000: 100nF ±10%, 63VDC, polyester, 7.3x2.5x6.5mm, P=5mm",
    },
    {
        "品牌": "Epcos",
        "型号": "B32529C0104K000",
        "系列": "B32529",
        "系列说明": "EPCOS/TDK MKT general purpose film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "63",
        "特殊用途": "RFI filtering / smoothing / general purpose",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.3x2.5x6.5",
        "长度（mm）": "7.3",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET/MKT 薄膜电容 0.1uF ±10% 63VDC EPCOS/TDK B32529 P=5.0mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/ja/search/capacitor/film/rfi_general/info?part_no=B32529C0104K000",
        "数据来源": "EPCOS/TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "EPCOS brand alias for B32529C0104K000 in TDK Product Center",
    },
    {
        "品牌": "Vishay",
        "型号": "MKP1848C51060JK2",
        "系列": "MKP1848C",
        "系列说明": "DC-link metallized polypropylene film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "600",
        "特殊用途": "DC-link / high ripple current film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P27.5",
        "尺寸（mm）": "32x9x19",
        "长度（mm）": "32",
        "宽度（mm）": "9",
        "高度（mm）": "19",
        "脚距（mm）": "27.5",
        "规格摘要": "PP 薄膜电容 1uF ±5% 600VDC Vishay MKP1848C P=27.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/doc?26015=",
        "数据来源": "Vishay official MKP1848C datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MKP1848C51060JK2: 600VDC, 1uF, height 19mm, PP, radial",
    },
    {
        "品牌": "CDE",
        "型号": "940C30P1K-F",
        "系列": "940C",
        "系列说明": "High dV/dt metallized polypropylene axial film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "3000",
        "特殊用途": "High pulse / high dV/dt snubber film capacitor",
        "安装方式": "插件",
        "封装代码": "AXIAL",
        "尺寸（mm）": "Ø22.5x46",
        "长度（mm）": "46",
        "直径（mm）": "22.5",
        "规格摘要": "PP 薄膜电容 0.1uF ±10% 3000VDC 轴向 940C",
        "生产状态": "Active",
        "工作温度": "-55~105℃",
        "官网链接": "https://www.cde.com/resources/catalogs/940C.pdf",
        "数据来源": "Cornell Dubilier / CDE official 940C datasheet",
        "数据状态": "官方PDF",
        "校验备注": "940C30P1K-F: 0.1uF, ±10%, 3000VDC, PP metallized, axial",
    },
    {
        "品牌": "Nichicon",
        "型号": "QYX2A104KTP",
        "系列": "QYX",
        "系列说明": "Foil type polyester film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "100",
        "特殊用途": "General purpose polyester film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P7.5",
        "尺寸（mm）": "11.0x5.5x14.0",
        "长度（mm）": "11.0",
        "宽度（mm）": "5.5",
        "高度（mm）": "14.0",
        "脚距（mm）": "7.5",
        "规格摘要": "PET 薄膜电容 0.1uF ±10% 100VDC Nichicon QYX P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.nichicon.co.jp/english/series_items/catalog_pdf/e-qyx.pdf",
        "数据来源": "Nichicon official QYX datasheet",
        "数据状态": "官方PDF",
        "校验备注": "QYX2A104KTP: 0.1uF, ±10%, 100VDC, T=5.5 W=11.0 H=14.0, P=7.5",
    },
    {
        "品牌": "TDK",
        "型号": "B72214S0271K101",
        "系列": "S14K275",
        "系列说明": "Leaded disk metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D431K, 275VAC, 350VDC, Vv=430V, Imax=4.5kA",
        "规格摘要": "TDK S14K275 14D431K 引线型压敏电阻 430V ±10% 275VAC P=7.5mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/en/search/protection/voltage/lead-disk-varistor/info?part_no=B72214S0271K101",
        "数据来源": "TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "S14K275: 275VAC, 350VDC, Vv=430V class, 14mm disk, P=7.5mm",
    },
    {
        "品牌": "Epcos",
        "型号": "B72214S0271K101",
        "系列": "S14K275",
        "系列说明": "EPCOS leaded disk metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D431K, 275VAC, 350VDC, Vv=430V, Imax=4.5kA",
        "规格摘要": "EPCOS S14K275 14D431K 引线型压敏电阻 430V ±10% 275VAC P=7.5mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/ja/search/protection/voltage/lead-disk-varistor/info?part_no=B72214S0271K101",
        "数据来源": "EPCOS/TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "EPCOS brand alias for B72214S0271K101 / S14K275",
    },
    {
        "品牌": "Bourns",
        "型号": "MOV-14D471K",
        "系列": "MOV-14D",
        "系列说明": "Metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA, 125J",
        "规格摘要": "Bourns MOV-14D471K 引线型压敏电阻 470V ±10% 300VAC P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.bourns.com/data/global/pdfs/MOV14D.pdf",
        "数据来源": "Bourns official MOV-14D datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MOV-14D471K: Vv=470V, 300VAC, 385VDC, Vc=775V, Imax=4.5kA, 14mm disk",
    },
    {
        "品牌": "Littelfuse",
        "型号": "V14E275P",
        "系列": "UltraMOV",
        "系列说明": "UltraMOV radial leaded varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "备注1": "14D431K, 275VAC, 350VDC, V_NDC=387-473V, Vc=710V, Imax=6kA",
        "规格摘要": "Littelfuse V14E275P 14D431K 引线型压敏电阻 430V级 275VAC",
        "生产状态": "Active",
        "官网链接": "https://www.littelfuse.com/products/overvoltage-protection/varistors/radial-leaded-varistors/ultramov/v14e275p",
        "数据来源": "Littelfuse official product page",
        "数据状态": "官方网页",
        "校验备注": "V14E275P: 275VAC, 350VDC, V_NDC 387-473V, Vc=710V, 14mm radial",
    },
    {
        "品牌": "Panasonic",
        "型号": "ERZV14D471",
        "系列": "ERZV",
        "系列说明": "ZNR surge absorber varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / ZNR",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=6kA, 125J",
        "规格摘要": "Panasonic ERZV14D471 14D471K 引线型压敏电阻 470V ±10% P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://industrial.panasonic.com/ww/products/pt/surge-components/models/ERZV14D471",
        "数据来源": "Panasonic official product page",
        "数据状态": "官方网页",
        "校验备注": "ERZV14D471: varistor voltage 470V, range 423-517V, 300VAC, 385VDC, 14 series",
    },
    {
        "品牌": "Vishay",
        "型号": "VDRS14T300BSE",
        "系列": "VDRS",
        "系列说明": "Through-hole metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA",
        "规格摘要": "Vishay VDRS14T300BSE 14D471K 引线型压敏电阻 470V级 300VAC",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/docs/29081/vdrs.pdf",
        "数据来源": "Vishay official VDRS datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VDRS14T300 series: 300VAC, 385VDC, Vv=470V, Vc=775V, 14mm disk class",
    },
    {
        "品牌": "Joyin",
        "型号": "JVR14N471K87PU5",
        "系列": "JVR",
        "系列说明": "Metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA, 140J",
        "规格摘要": "Joyin JVR14N471K87PU5 14D471K 引线型压敏电阻 470V ±10% P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.joyin.com.tw/storage/system/product/pdf/MOV_JVR_datasheet20250305.pdf",
        "数据来源": "Joyin official JVR datasheet",
        "数据状态": "官方PDF",
        "校验备注": "JVR14N471K: Vv=470V, 300VAC, 385VDC, Vc=775V, Imax=4.5kA, energy 140J",
    },
    {
        "品牌": "Abracon",
        "型号": "ABM3B-8.000MHZ-B2-T",
        "系列": "ABM3B",
        "系列说明": "Ceramic SMD quartz crystal",
        "器件类型": "晶振",
        "容值": "8",
        "容值单位": "MHz",
        "频率": "8",
        "频率单位": "MHz",
        "频差（ppm）": "20",
        "容值误差": "20PPM",
        "负载电容（pF）": "18",
        "安装方式": "贴片",
        "尺寸（inch）": "5032",
        "封装代码": "5032",
        "尺寸（mm）": "5.0x3.2x1.1",
        "长度（mm）": "5.0",
        "宽度（mm）": "3.2",
        "高度（mm）": "1.1",
        "备注1": "8MHz, CL=18pF, ESR max 200ohm, -20 to +70C option",
        "规格摘要": "Abracon ABM3B 8MHz 18pF ±20ppm 5032 SMD crystal",
        "生产状态": "Active",
        "官网链接": "https://abracon.com/Resonators/abm3b.pdf",
        "数据来源": "Abracon official ABM3B datasheet",
        "数据状态": "官方PDF",
        "校验备注": "ABM3B series: 8-50MHz fundamental, 5.0x3.2x1.1mm package; B2 code=18pF ±20ppm",
    },
    {
        "品牌": "TXC",
        "型号": "7M-16.000MAHE-T",
        "系列": "7M",
        "系列说明": "SMD quartz crystal",
        "器件类型": "晶振",
        "容值": "16",
        "容值单位": "MHz",
        "频率": "16",
        "频率单位": "MHz",
        "频差（ppm）": "30",
        "容值误差": "30PPM",
        "负载电容（pF）": "12",
        "安装方式": "贴片",
        "尺寸（inch）": "3225",
        "封装代码": "3225",
        "尺寸（mm）": "3.2x2.5x0.8",
        "长度（mm）": "3.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "0.8",
        "备注1": "16MHz, CL=12pF, ESR max 80ohm, -40 to +85C",
        "规格摘要": "TXC 7M 16MHz 12pF ±30ppm 3225 SMD crystal",
        "生产状态": "Active",
        "官网链接": "https://www.digikey.ca/en/products/detail/txc-corporation/7M-16-000MAHE-T/3585857",
        "数据来源": "DigiKey authorized TXC product page",
        "数据状态": "授权分销参数",
        "校验备注": "7M-16.000MAHE-T: Active, 16MHz, 12pF, ±30ppm, 3.2x2.5mm package",
    },
    {
        "品牌": "NDK",
        "型号": "NX3225GA-16.000M-STD-CRG-2",
        "系列": "NX3225GA",
        "系列说明": "Compact SMD crystal unit",
        "器件类型": "晶振",
        "容值": "16",
        "容值单位": "MHz",
        "频率": "16",
        "频率单位": "MHz",
        "频差（ppm）": "20",
        "容值误差": "20PPM",
        "负载电容（pF）": "8",
        "安装方式": "贴片",
        "尺寸（inch）": "3225",
        "封装代码": "3225",
        "尺寸（mm）": "3.2x2.5x0.75",
        "长度（mm）": "3.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "0.75",
        "备注1": "9.8-50MHz range, CL=8pF, fundamental, -40 to +85C",
        "规格摘要": "NDK NX3225GA 16MHz 8pF ±20ppm 3225 SMD crystal",
        "生产状态": "Active",
        "官网链接": "https://www.ndk.com/en/products/lineup/crystal-unit/NX3225GA-standard.html",
        "数据来源": "NDK official NX3225GA product page",
        "数据状态": "官方网页",
        "校验备注": "NX3225GA standard: 9.8-50MHz, 3.2x2.5x0.75mm, CL=8pF, ±20ppm",
    },
    {
        "品牌": "Kyocera",
        "型号": "CX3225SB16000D0GLLCC",
        "系列": "CX3225SB",
        "系列说明": "3225 size crystal unit for consumer products",
        "器件类型": "晶振",
        "容值": "16",
        "容值单位": "MHz",
        "频率": "16",
        "频率单位": "MHz",
        "频差（ppm）": "15",
        "容值误差": "15PPM",
        "负载电容（pF）": "8",
        "安装方式": "贴片",
        "尺寸（inch）": "3225",
        "封装代码": "3225",
        "尺寸（mm）": "3.2x2.5x0.6",
        "长度（mm）": "3.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "0.6",
        "备注1": "16MHz, CL=8pF, temperature characteristics ±20ppm, -30 to +85C",
        "规格摘要": "Kyocera CX3225SB 16MHz 8pF ±15ppm 3225 SMD crystal",
        "生产状态": "Active",
        "官网链接": "https://ele.kyocera.com/en/product/crystal-device/crystal_units/cx3225sb/cx3225sb16000d0gllcc/",
        "数据来源": "Kyocera official product page",
        "数据状态": "官方网页",
        "校验备注": "CX3225SB16000D0GLLCC: 16MHz, 3.2x2.5mm, height 0.60mm, CL=8pF, ±15ppm",
    },
    {
        "品牌": "Murata",
        "型号": "XRCGB16M000FXN02R0",
        "系列": "XRCGB",
        "系列说明": "SMD crystal unit for consumer applications",
        "器件类型": "晶振",
        "容值": "16",
        "容值单位": "MHz",
        "频率": "16",
        "频率单位": "MHz",
        "频差（ppm）": "30",
        "容值误差": "30PPM",
        "安装方式": "贴片",
        "尺寸（inch）": "2016",
        "封装代码": "2016",
        "尺寸（mm）": "2.0x1.6x0.7",
        "长度（mm）": "2.0",
        "宽度（mm）": "1.6",
        "高度（mm）": "0.7",
        "备注1": "XRCGB series, 16-50MHz, selectable 6/8/10pF load capacitance",
        "规格摘要": "Murata XRCGB 16MHz ±30ppm 2016 SMD crystal",
        "生产状态": "Active",
        "官网链接": "https://www.murata.com/en-us/products/timingdevice/crystalu/overview/lineup/xrcgb",
        "数据来源": "Murata official XRCGB lineup page",
        "数据状态": "官方网页",
        "校验备注": "XRCGB-F-N/M series covers 16MHz, 2.0x1.6x0.7mm; load capacitance depends on part suffix/design",
    },
    {
        "品牌": "KDS",
        "型号": "DSX321G-16.000-7AD01600A7T",
        "系列": "DSX321G",
        "系列说明": "SMD crystal resonator",
        "器件类型": "晶振",
        "容值": "16",
        "容值单位": "MHz",
        "频率": "16",
        "频率单位": "MHz",
        "安装方式": "贴片",
        "尺寸（inch）": "3225",
        "封装代码": "3225",
        "尺寸（mm）": "3.2x2.5x0.8",
        "长度（mm）": "3.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "0.8",
        "备注1": "DSX321G 16MHz SMD crystal resonator",
        "规格摘要": "KDS DSX321G 16MHz 3225 SMD crystal resonator",
        "生产状态": "Active",
        "官网链接": "https://www.kds.info/wp-content/themes/kds/asset/img/pdf/DSX321G_7AD01600A7T.pdf",
        "数据来源": "KDS official DSX321G type specification",
        "数据状态": "官方PDF",
        "校验备注": "DSX321G_7AD01600A7T official type specification for 16.000MHz DSX321G",
    },
    {
        "品牌": "Abracon",
        "型号": "ASE-25.000MHZ-LC-T",
        "系列": "ASE",
        "系列说明": "3.3V CMOS SMD crystal oscillator",
        "器件类型": "振荡器",
        "容值": "25",
        "容值单位": "MHz",
        "输出频率": "25",
        "频率单位": "MHz",
        "频差（ppm）": "50",
        "容值误差": "50PPM",
        "耐压（V）": "3.3",
        "电源电压": "3.3",
        "输出类型": "CMOS",
        "安装方式": "贴片",
        "尺寸（inch）": "3225",
        "封装代码": "3225",
        "尺寸（mm）": "3.2x2.5x1.2",
        "长度（mm）": "3.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "1.2",
        "备注1": "3.3V CMOS, output load 15pF, tri-state, -40 to +85C option",
        "规格摘要": "Abracon ASE 25MHz 3.3V CMOS ±50ppm 3225 SMD oscillator",
        "生产状态": "Active",
        "官网链接": "https://abracon.com/Oscillators/ASEseries.pdf",
        "数据来源": "Abracon ASE series datasheet",
        "数据状态": "原厂PDF",
        "校验备注": "ASE ordering: C=±50ppm stability, L=-40 to +85C, T=tape and reel",
    },
    {
        "品牌": "TXC",
        "型号": "7C-25.000MBA-T",
        "系列": "7C",
        "系列说明": "MHz CMOS oscillator",
        "器件类型": "振荡器",
        "容值": "25",
        "容值单位": "MHz",
        "输出频率": "25",
        "频率单位": "MHz",
        "频差（ppm）": "25",
        "容值误差": "25PPM",
        "耐压（V）": "3.3",
        "电源电压": "3.3",
        "输出类型": "CMOS",
        "占空比": "40 to 60",
        "安装方式": "贴片",
        "尺寸（inch）": "5032",
        "封装代码": "5032",
        "尺寸（mm）": "5.0x3.2x1.2",
        "长度（mm）": "5.0",
        "宽度（mm）": "3.2",
        "高度（mm）": "1.2",
        "备注1": "25MHz CMOS XO, 3.3V, enable/disable, -10 to +70C",
        "规格摘要": "TXC 7C 25MHz 3.3V CMOS ±25ppm 5032 SMD oscillator",
        "生产状态": "Active",
        "官网链接": "https://www.digikey.com/en/products/detail/txc-corporation/7C-25-000MBA-T/2207809",
        "数据来源": "TXC 7C official datasheet plus DigiKey product page",
        "数据状态": "原厂PDF/授权分销参数",
        "校验备注": "7C series: 1-170MHz, 5.0x3.2x1.2mm, CMOS; MBA code=3.3V ±25ppm",
    },
    {
        "品牌": "NDK",
        "型号": "NP2520SB-156.250M-NSC5397B",
        "系列": "NP2520SB",
        "系列说明": "LVDS differential output SPXO",
        "器件类型": "振荡器",
        "容值": "156.25",
        "容值单位": "MHz",
        "输出频率": "156.25",
        "频率单位": "MHz",
        "频差（ppm）": "50",
        "容值误差": "50PPM",
        "耐压（V）": "3.3",
        "电源电压": "3.3",
        "输出类型": "LVDS",
        "占空比": "45 to 55",
        "安装方式": "贴片",
        "尺寸（inch）": "2520",
        "封装代码": "2520",
        "尺寸（mm）": "2.5x2.0x0.8",
        "长度（mm）": "2.5",
        "宽度（mm）": "2.0",
        "高度（mm）": "0.8",
        "备注1": "100-170MHz range, LVDS, 2.5V or 3.3V, max ±50ppm",
        "规格摘要": "NDK NP2520SB 156.25MHz 3.3V LVDS ±50ppm 2520 SMD oscillator",
        "生产状态": "Active",
        "官网链接": "https://www.ndk.com/cn/products/lineup/crystal-oscillator/NP2520SB.html",
        "数据来源": "NDK official NP2520SB product page",
        "数据状态": "官方网页",
        "校验备注": "NP2520SB: 100-170MHz, 2.5x2.0x0.8mm, +2.5/+3.3V, LVDS, max ±50ppm",
    },
    {
        "品牌": "Kyocera",
        "型号": "KC2520K33.3333C1GE00",
        "系列": "KC2520K",
        "系列说明": "2520 size CMOS output SPXO",
        "器件类型": "振荡器",
        "容值": "33.3333",
        "容值单位": "MHz",
        "输出频率": "33.3333",
        "频率单位": "MHz",
        "频差（ppm）": "50",
        "容值误差": "50PPM",
        "耐压（V）": "1.8/2.5/3.3",
        "电源电压": "1.8/2.5/3.3",
        "输出类型": "CMOS",
        "安装方式": "贴片",
        "尺寸（inch）": "2520",
        "封装代码": "2520",
        "尺寸（mm）": "2.5x2.0x0.8",
        "长度（mm）": "2.5",
        "宽度（mm）": "2.0",
        "高度（mm）": "0.8",
        "备注1": "33.3333MHz, CMOS, INH function, -40 to +85C",
        "规格摘要": "Kyocera KC2520K 33.3333MHz CMOS ±50ppm 2520 SMD oscillator",
        "生产状态": "Active",
        "官网链接": "https://ele.kyocera.com/en/product/crystal-device/clock_oscillatorsspxo/kc2520k/kc2520k33.3333c1ge00",
        "数据来源": "Kyocera official product page",
        "数据状态": "官方网页",
        "校验备注": "KC2520K33.3333C1GE00: 33.3333MHz, CMOS, 2.5x2.0mm, height 0.80mm, ±50ppm",
    },
    {
        "品牌": "SiTime",
        "型号": "SiT1602BI-13-33E-25.000000",
        "系列": "SiT1602",
        "系列说明": "LVCMOS oscillator",
        "器件类型": "振荡器",
        "容值": "25",
        "容值单位": "MHz",
        "输出频率": "25",
        "频率单位": "MHz",
        "频差（ppm）": "50",
        "容值误差": "50PPM",
        "耐压（V）": "3.3",
        "电源电压": "3.3",
        "输出类型": "LVCMOS",
        "安装方式": "贴片",
        "尺寸（inch）": "2520",
        "封装代码": "2520",
        "尺寸（mm）": "2.5x2.0",
        "长度（mm）": "2.5",
        "宽度（mm）": "2.0",
        "备注1": "25MHz, 3.3V, -40 to +85C, OE feature pin",
        "规格摘要": "SiTime SiT1602BI 25MHz 3.3V LVCMOS ±50ppm 2520 oscillator",
        "生产状态": "Active",
        "官网链接": "https://www.sitime.com/parts/sit1602bi-13-33e-25000000",
        "数据来源": "SiTime official product page",
        "数据状态": "官方网页",
        "校验备注": "SiT1602BI-13-33E-25.000000: 25MHz, ±50ppm, -40 to +85C, 3.3V, 2.5x2.0mm",
    },
    {
        "品牌": "KNSCHA(科尼盛)",
        "型号": "DHF025M687G160S1AA",
        "系列": "DHF",
        "系列说明": "KNSCHA DHF aluminum electrolytic capacitor",
        "器件类型": "铝电解电容",
        "容值": "680",
        "容值单位": "UF",
        "容值误差": "20",
        "耐压（V）": "25",
        "安装方式": "插件",
        "封装代码": "DIP/P3.5",
        "尺寸（mm）": "D8x16",
        "直径（mm）": "8",
        "高度（mm）": "16",
        "脚距（mm）": "3.5",
        "工作温度": "105℃",
        "寿命（h）": "5000",
        "极性": "有极性",
        "纹波电流": "1.45A",
        "规格摘要": "KNSCHA DHF 680uF ±20% 25V DIP D8xL16mm P=3.5mm 5000h@105℃",
        "生产状态": "Active",
        "官网链接": "https://www.lcsc.com/product-image/C49309224.html",
        "数据来源": "LCSC product page",
        "数据状态": "授权分销/公开参数",
        "校验备注": "DHF025M687G160S1AA: 680uF, ±20%, 25V, DIP, D8xL16mm, P=3.5mm, 5000h@105℃, ripple 1.45A",
    },
]


def ensure_columns(conn):
    return [row[1] for row in conn.execute("PRAGMA table_info(components)").fetchall()]


def clean_model_key(value):
    return str(value or "").upper().replace("-", "").replace(" ", "").replace("_", "")


def sync_rows(dry_run=False):
    if not os.path.exists(DB_PATH):
        raise FileNotFoundError(DB_PATH)
    conn = sqlite3.connect(DB_PATH)
    try:
        columns = ensure_columns(conn)
        now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        rows = []
        for seed in SEED_ROWS:
            row = {col: "" for col in columns}
            row.update({key: value for key, value in seed.items() if key in row})
            if "校验时间" in row:
                row["校验时间"] = now
            rows.append(row)
        if dry_run:
            return len(rows)

        for row in rows:
            conn.execute(
                "DELETE FROM components WHERE [品牌] = ? AND "
                "REPLACE(REPLACE(REPLACE(UPPER(IFNULL([型号], '')), '-', ''), ' ', ''), '_', '') = ?",
                (row.get("品牌", ""), clean_model_key(row.get("型号", ""))),
            )
        placeholders = ",".join(["?"] * len(columns))
        column_sql = ",".join(f"[{col}]" for col in columns)
        insert_sql = f"INSERT INTO components ({column_sql}) VALUES ({placeholders})"
        conn.executemany(insert_sql, [[row.get(col, "") for col in columns] for row in rows])
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Sync source-backed passive gap seed rows into components.db")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    count = sync_rows(dry_run=args.dry_run)
    action = "would_sync" if args.dry_run else "synced"
    print(f"{action}_passive_gap_rows={count}")


if __name__ == "__main__":
    main()
