import argparse
import datetime as dt
import os
import sqlite3


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "components.db")


SEED_ROWS = [
    {
        "品牌": "AOSMD",
        "型号": "AO3400A",
        "系列": "AO3400A",
        "系列说明": "30V N-Channel MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "30",
        "额定电流": "5.7A",
        "DCR": "Rds(on) 26.5mΩ@10V; 32mΩ@4.5V; 48mΩ@2.5V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "30V N沟道 MOSFET 5.7A Rds(on) 26.5mΩ@10V SOT-23",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.aosmd.com/res/data_sheets/AO3400A.pdf",
        "数据来源": "AOSMD official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VDS=30V, ID=5.7A, Rds(on)<26.5mΩ@10V, SOT23",
    },
    {
        "品牌": "AOSMD",
        "型号": "AO3401A",
        "系列": "AO3401A",
        "系列说明": "30V P-Channel MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "P沟道 MOSFET",
        "极性": "P沟道",
        "耐压（V）": "30",
        "额定电流": "4A",
        "DCR": "Rds(on) 50mΩ@10V; 60mΩ@4.5V; 85mΩ@2.5V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "30V P沟道 MOSFET 4A Rds(on) 50mΩ@10V SOT-23",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.aosmd.com/res/data_sheets/AO3401A.pdf",
        "数据来源": "AOSMD official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VDS=-30V, ID=-4.0A, Rds(on)<50mΩ@-10V, SOT23",
    },
    {
        "品牌": "Infineon",
        "型号": "IRLZ44N",
        "系列": "IRLZ44N",
        "系列说明": "Logic-level N-Channel Power MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 逻辑电平 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "55",
        "额定电流": "47A",
        "DCR": "Rds(on) 22mΩ@10V; 35mΩ@4.5V",
        "封装代码": "TO-220",
        "安装方式": "THT",
        "规格摘要": "55V N沟道逻辑电平 MOSFET 47A Rds(on) 22mΩ@10V TO-220",
        "生产状态": "Active",
        "工作温度": "-55~175℃",
        "官网链接": "https://www.infineon.com/part/IRLZ44N",
        "数据来源": "Infineon official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=55V, ID=47A, Rds(on) max 22mΩ@10V, package TO-220",
    },
    {
        "品牌": "Infineon",
        "型号": "IRF540N",
        "系列": "IRF540N",
        "系列说明": "N-Channel Power MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "100",
        "额定电流": "33A",
        "DCR": "Rds(on) 44mΩ@10V",
        "封装代码": "TO-220",
        "安装方式": "THT",
        "规格摘要": "100V N沟道 MOSFET 33A Rds(on) 44mΩ@10V TO-220",
        "生产状态": "Active",
        "工作温度": "-55~175℃",
        "官网链接": "https://www.infineon.com/part/IRF540N",
        "数据来源": "Infineon official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=100V, ID=33A, Rds(on) max 44mΩ@10V, package TO-220",
    },
    {
        "品牌": "onsemi",
        "型号": "2N7002",
        "系列": "2N7002",
        "系列说明": "Small Signal N-Channel MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 小信号 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "60",
        "额定电流": "0.115A",
        "DCR": "Rds(on) 7.5Ω@10V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "60V N沟道小信号 MOSFET 0.115A Rds(on) 7.5Ω SOT-23",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.onsemi.cn/products/discrete-power-modules/mosfets/small-signal-mosfets/2n7002",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=60V, ID=0.115A, Rds(on)=7.5Ω, SOT-23",
    },
    {
        "品牌": "onsemi",
        "型号": "BSS138",
        "系列": "BSS138",
        "系列说明": "Logic-level N-Channel Small Signal MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 逻辑电平小信号 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "50",
        "额定电流": "0.22A",
        "DCR": "Rds(on) 3.5Ω@10V; 6Ω@4.5V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "50V N沟道小信号 MOSFET 0.22A Rds(on) 3.5Ω SOT-23",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.onsemi.cn/products/discrete-power-modules/mosfets/small-signal-mosfets/BSS138",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=50V, ID=0.22A, Rds(on)=3.5Ω@10V / 6Ω@4.5V, SOT-23",
    },
    {
        "品牌": "Nexperia",
        "型号": "MMBT3904",
        "系列": "MMBT3904",
        "系列说明": "NPN switching transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN switching transistor",
        "极性": "NPN",
        "耐压（V）": "40",
        "额定电流": "0.2A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "40V 200mA NPN switching transistor SOT-23",
        "生产状态": "Active",
        "工作温度": "-65~150℃",
        "官网链接": "https://assets.nexperia.com/documents/data-sheet/MMBT3904.pdf",
        "数据来源": "Nexperia official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VCEO=40V, IC=200mA, SOT23",
    },
    {
        "品牌": "Nexperia",
        "型号": "1N4148",
        "系列": "1N4148",
        "系列说明": "High-speed switching diode",
        "器件类型": "二极管",
        "特殊用途": "高速开关二极管",
        "耐压（V）": "100",
        "额定电流": "0.45A",
        "封装代码": "DO-35",
        "安装方式": "THT",
        "规格摘要": "100V high-speed switching diode IFRM 450mA DO-35/SOD27",
        "生产状态": "End of life / TAK CHEONG licensed production",
        "官网链接": "https://www.nexperia.com/product/1N4148",
        "数据来源": "Nexperia official product page",
        "数据状态": "官方网页",
        "校验备注": "Continuous reverse voltage 100V; repetitive peak forward current 450mA; SOD27/DO-35",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "SMBJ5.0CA",
        "系列": "SMBJ",
        "系列说明": "600W Surface Mount Transient Voltage Suppressor",
        "器件类型": "TVS二极管",
        "特殊用途": "TVS二极管",
        "极性": "双向",
        "耐压（V）": "5",
        "封装代码": "SMB",
        "安装方式": "SMT",
        "规格摘要": "600W 双向 TVS VRWM 5V VBR 6.4-7.23V SMB",
        "生产状态": "Active",
        "官网链接": "https://www.diodes.com/part/view/SMBJ5.0CA",
        "数据来源": "Diodes official product page",
        "数据状态": "官方网页",
        "校验备注": "VRWM=5V, VBR=6.4-7.23V, VC=9.2V, 600W, SMB, bidirectional",
    },
    {
        "品牌": "Vishay",
        "型号": "SS34",
        "系列": "SS32-SS36",
        "系列说明": "Surface Mount Schottky Barrier Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "3A",
        "封装代码": "DO-214AB/SMC",
        "安装方式": "SMT",
        "规格摘要": "40V 3A Schottky rectifier DO-214AB/SMC",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.vishay.com/docs/88751/ss32.pdf",
        "数据来源": "Vishay official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "SS34 in SS32-SS36 family: VRRM=40V, IF(AV)=3.0A, DO-214AB(SMC)",
    },
    {
        "品牌": "Nexperia",
        "型号": "SS34FA",
        "系列": "SS34FA",
        "系列说明": "40 V, 3 A low VF Schottky barrier rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "3A",
        "封装代码": "SOD123FL",
        "安装方式": "SMT",
        "规格摘要": "40V 3A low VF Schottky barrier rectifier SOD123FL",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/product/SS34FA",
        "数据来源": "Nexperia official product page",
        "数据状态": "官方网页",
        "校验备注": "VR<=40V, IF(AV)<=3A, SOD123FL",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "BAT54",
        "系列": "BAT54",
        "系列说明": "Schottky barrier diode",
        "器件类型": "二极管",
        "特殊用途": "肖特基二极管",
        "耐压（V）": "30",
        "额定电流": "0.2A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "30V 200mA Schottky barrier diode SOT-23",
        "生产状态": "Active / PCN EOL pending",
        "官网链接": "https://www.diodes.com/part/view/BAT54",
        "数据来源": "Diodes official product page",
        "数据状态": "官方网页",
        "校验备注": "VRRM=30V, IFM=200mA, SOT23",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "BAV99",
        "系列": "BAV99",
        "系列说明": "Dual Surface Mount Switching Diode",
        "器件类型": "二极管",
        "特殊用途": "双开关二极管",
        "耐压（V）": "100",
        "额定电流": "0.215A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "100V 215mA dual surface mount switching diode SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.diodes.com/part/view/BAV99",
        "数据来源": "Diodes official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "Dual switching diode, SOT23; verify array topology before drop-in replacement",
    },
    {
        "品牌": "STMicroelectronics",
        "型号": "1N5819",
        "系列": "1N5819",
        "系列说明": "40 V, 1 A axial Power Schottky Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "1A",
        "封装代码": "DO-41",
        "安装方式": "THT",
        "规格摘要": "40V 1A axial Schottky rectifier DO-41",
        "生产状态": "Active",
        "官网链接": "https://www.st.com/content/st_com/en/products/diodes-and-rectifiers/schottky-barrier-diodes/power-schottky/power-schottky-medium-vf-and-ir/1n5819.html",
        "数据来源": "ST official product page",
        "数据状态": "官方网页",
        "校验备注": "VRRM=40V, IF(AV)=1A, DO-41 plastic",
    },
    {
        "品牌": "Rectron",
        "型号": "S8050",
        "系列": "S8050",
        "系列说明": "NPN silicon transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN transistor",
        "极性": "NPN",
        "耐压（V）": "25",
        "额定电流": "0.5A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "25V 500mA NPN silicon transistor SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.rectron.com/public/product_datasheets/s8050.pdf",
        "数据来源": "Rectron official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VCEO=25V; VCE(sat) test at IC=500mA; SOT-23",
    },
    {
        "品牌": "Nexperia",
        "型号": "BC817",
        "系列": "BC817",
        "系列说明": "45 V, 500 mA NPN general-purpose transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN general-purpose transistor",
        "极性": "NPN",
        "耐压（V）": "45",
        "额定电流": "0.5A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "45V 500mA NPN general-purpose transistor SOT-23",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/product/BC817",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VCEO=45V, IC=500mA, SOT23",
    },
    {
        "品牌": "Nexperia",
        "型号": "BC807",
        "系列": "BC807",
        "系列说明": "45 V, 500 mA PNP general-purpose transistor",
        "器件类型": "三极管",
        "特殊用途": "PNP general-purpose transistor",
        "极性": "PNP",
        "耐压（V）": "45",
        "额定电流": "0.5A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "45V 500mA PNP general-purpose transistor SOT-23",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/group/bc807-series",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VCEO=45V, IC=500mA, SOT23",
    },
    {
        "品牌": "Nexperia",
        "型号": "MMBT3906",
        "系列": "MMBT3906",
        "系列说明": "40 V, 200 mA PNP switching transistor",
        "器件类型": "三极管",
        "特殊用途": "PNP switching transistor",
        "极性": "PNP",
        "耐压（V）": "40",
        "额定电流": "0.2A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "40V 200mA PNP switching transistor SOT-23",
        "生产状态": "Production",
        "官网链接": "https://assets.nexperia.com/documents/data-sheet/MMBT3906.pdf",
        "数据来源": "Nexperia official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VCEO=40V, IC=200mA, SOT23",
    },
    {
        "品牌": "Vishay",
        "型号": "SI2302CDS",
        "系列": "SI2302CDS",
        "系列说明": "N-Channel 20 V (D-S) MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "20",
        "额定电流": "2.9A",
        "DCR": "Rds(on) 57mΩ@4.5V; 75mΩ@2.5V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "20V N沟道 MOSFET 2.9A Rds(on) 57mΩ@4.5V SOT-23",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.vishay.com/docs/68645/si2302cds.pdf",
        "数据来源": "Vishay official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VDS=20V, ID=2.9A, Rds(on) max 57mΩ@4.5V, SOT-23",
    },
    {
        "品牌": "Infineon",
        "型号": "IRFZ44N",
        "系列": "IRFZ44N",
        "系列说明": "55V Single N-Channel Power MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "55",
        "额定电流": "49A",
        "DCR": "Rds(on) 17.5mΩ@10V",
        "封装代码": "TO-220",
        "安装方式": "THT",
        "规格摘要": "55V N沟道 MOSFET 49A Rds(on) 17.5mΩ@10V TO-220",
        "生产状态": "Active",
        "工作温度": "-55~175℃",
        "官网链接": "https://www.infineon.com/part/IRFZ44N",
        "数据来源": "Infineon official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=55V, ID=49A, Rds(on)=17.5mΩ@10V, TO-220",
    },
    {
        "品牌": "onsemi",
        "型号": "1N4007",
        "系列": "1N4001-1N4007",
        "系列说明": "Axial lead standard recovery rectifier",
        "器件类型": "二极管",
        "特殊用途": "通用整流二极管",
        "耐压（V）": "1000",
        "额定电流": "1A",
        "封装代码": "DO-41",
        "安装方式": "THT",
        "规格摘要": "1000V 1A standard recovery rectifier DO-41",
        "生产状态": "Active",
        "官网链接": "https://www.onsemi.com/products/discrete-power-modules/rectifiers/standard-recovery-rectifiers/1n4007",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VRRM=1000V, IO=1A, DO-41 axial",
    },
    {
        "品牌": "onsemi",
        "型号": "MBR0520LT1G",
        "系列": "MBR0520L",
        "系列说明": "Surface Mount Schottky Power Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "20",
        "额定电流": "0.5A",
        "封装代码": "SOD-123",
        "安装方式": "SMT",
        "规格摘要": "20V 0.5A Schottky power rectifier SOD-123",
        "生产状态": "Active",
        "官网链接": "https://www.onsemi.com/products/discrete-power-modules/rectifiers/schottky-rectifiers/mbr0520lt1g",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VRRM=20V, IF(AV)=0.5A, SOD-123",
    },
    {
        "品牌": "Vishay",
        "型号": "SS14",
        "系列": "SS12-SS110",
        "系列说明": "Surface Mount Schottky Barrier Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "1A",
        "封装代码": "SMA/DO-214AC",
        "安装方式": "SMT",
        "规格摘要": "40V 1A Schottky rectifier SMA/DO-214AC",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/docs/88746/ss12.pdf",
        "数据来源": "Vishay official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "SS14 in SS12-SS110 family: VRRM=40V, IF(AV)=1A, SMA",
    },
    {
        "品牌": "Vishay",
        "型号": "SS24",
        "系列": "SS22-SS210",
        "系列说明": "Surface Mount Schottky Barrier Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "2A",
        "封装代码": "SMB/DO-214AA",
        "安装方式": "SMT",
        "规格摘要": "40V 2A Schottky rectifier SMB/DO-214AA",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/docs/88750/ss22.pdf",
        "数据来源": "Vishay official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "SS24 in SS22-SS210 family: VRRM=40V, IF(AV)=2A, SMB",
    },
    {
        "品牌": "Vishay",
        "型号": "SS54",
        "系列": "SS52-SS510",
        "系列说明": "Surface Mount Schottky Barrier Rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "5A",
        "封装代码": "SMC/DO-214AB",
        "安装方式": "SMT",
        "规格摘要": "40V 5A Schottky rectifier SMC/DO-214AB",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/docs/88747/ss52.pdf",
        "数据来源": "Vishay official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "SS54 in SS52-SS510 family: VRRM=40V, IF(AV)=5A, SMC",
    },
    {
        "品牌": "onsemi",
        "型号": "MMBT2222A",
        "系列": "MMBT2222A",
        "系列说明": "NPN general purpose amplifier transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN general-purpose transistor",
        "极性": "NPN",
        "耐压（V）": "40",
        "额定电流": "0.6A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "40V 600mA NPN general purpose transistor SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.onsemi.com/products/discrete-power-modules/general-purpose-and-low-vcesat-transistors/mmbt2222a",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VCEO=40V, IC=600mA, SOT-23",
    },
    {
        "品牌": "onsemi",
        "型号": "MMBT2907A",
        "系列": "MMBT2907A",
        "系列说明": "PNP general purpose amplifier transistor",
        "器件类型": "三极管",
        "特殊用途": "PNP general-purpose transistor",
        "极性": "PNP",
        "耐压（V）": "60",
        "额定电流": "0.6A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "60V 600mA PNP general purpose transistor SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.onsemi.com/products/discrete-power-modules/general-purpose-and-low-vcesat-transistors/mmbt2907a",
        "数据来源": "onsemi official product page",
        "数据状态": "官方网页",
        "校验备注": "VCEO=60V, IC=600mA, SOT-23",
    },
    {
        "品牌": "Nexperia",
        "型号": "BC847",
        "系列": "BC847",
        "系列说明": "45 V, 100 mA NPN general-purpose transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN general-purpose transistor",
        "极性": "NPN",
        "耐压（V）": "45",
        "额定电流": "0.1A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "45V 100mA NPN general-purpose transistor SOT-23",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/product/BC847",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VCEO=45V, IC=100mA, SOT23",
    },
    {
        "品牌": "Nexperia",
        "型号": "BC857",
        "系列": "BC857",
        "系列说明": "45 V, 100 mA PNP general-purpose transistor",
        "器件类型": "三极管",
        "特殊用途": "PNP general-purpose transistor",
        "极性": "PNP",
        "耐压（V）": "45",
        "额定电流": "0.1A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "45V 100mA PNP general-purpose transistor SOT-23",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/product/BC857",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VCEO=45V, IC=100mA, SOT23",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "SMAJ5.0CA",
        "系列": "SMAJ",
        "系列说明": "400W Surface Mount Transient Voltage Suppressor",
        "器件类型": "TVS二极管",
        "特殊用途": "TVS二极管",
        "极性": "双向",
        "耐压（V）": "5",
        "封装代码": "SMA",
        "安装方式": "SMT",
        "规格摘要": "400W 双向 TVS VRWM 5V SMA",
        "生产状态": "Active",
        "官网链接": "https://www.diodes.com/part/view/SMAJ5.0CA",
        "数据来源": "Diodes official product page",
        "数据状态": "官方网页",
        "校验备注": "VRWM=5V, 400W peak pulse power, SMA, bidirectional",
    },
    {
        "品牌": "Littelfuse",
        "型号": "SMBJ12CA",
        "系列": "SMBJ",
        "系列说明": "600W Surface Mount TVS Diode",
        "器件类型": "TVS二极管",
        "特殊用途": "TVS二极管",
        "极性": "双向",
        "耐压（V）": "12",
        "封装代码": "SMB",
        "安装方式": "SMT",
        "规格摘要": "600W 双向 TVS VRWM 12V SMB",
        "生产状态": "Active",
        "官网链接": "https://www.littelfuse.com/products/tvs-diodes/surface-mount-tvs-diodes/smbj/smbj12ca.aspx",
        "数据来源": "Littelfuse official product page",
        "数据状态": "官方网页",
        "校验备注": "VRWM=12V, 600W peak pulse power, SMB, bidirectional",
    },
    {
        "品牌": "STMicroelectronics",
        "型号": "STP55NF06L",
        "系列": "STP55NF06L",
        "系列说明": "N-channel 60V StripFET II Power MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道功率 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "60",
        "额定电流": "55A",
        "DCR": "Rds(on) <18mΩ@10V",
        "封装代码": "TO-220",
        "安装方式": "THT",
        "规格摘要": "60V N沟道功率 MOSFET 55A Rds(on)<18mΩ TO-220",
        "生产状态": "Active",
        "工作温度": "-55~175℃",
        "官网链接": "https://www.st.com/resource/en/datasheet/stp55nf06l.pdf",
        "数据来源": "STMicroelectronics official datasheet/product page",
        "数据状态": "官方PDF",
        "校验备注": "VDS=60V, ID=55A, Rds(on)<0.018Ω, TO-220",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "DMN3024LSD",
        "系列": "DMN3024LSD",
        "系列说明": "Dual N-channel 30V enhancement mode MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "双N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "30",
        "额定电流": "7.2A",
        "DCR": "Rds(on) 24mΩ@10V; 36mΩ@4.5V",
        "封装代码": "SO-8",
        "安装方式": "SMT",
        "规格摘要": "30V 双N沟道 MOSFET 7.2A Rds(on) 24mΩ SO-8",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.diodes.com/datasheet/download/DMN3024LSD.pdf",
        "数据来源": "Diodes Incorporated official datasheet",
        "数据状态": "官方PDF",
        "校验备注": "V(BR)DSS=30V, ID=7.2A@TA=25℃, Rds(on)=24mΩ@10V, SO-8",
    },
    {
        "品牌": "ROHM",
        "型号": "RQ3E100BNTB1",
        "系列": "RQ3E100BN",
        "系列说明": "Nch 30V 21A Power MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道功率 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "30",
        "额定电流": "21A",
        "DCR": "Rds(on) 7.7mΩ typ@10V; 11mΩ typ@4.5V",
        "封装代码": "HSMT8",
        "安装方式": "SMT",
        "尺寸（mm）": "3.3x3.3x0.9",
        "规格摘要": "30V N沟道功率 MOSFET 21A Rds(on) 7.7mΩ typ HSMT8",
        "生产状态": "Recommended",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.rohm.com/products/mosfets/small-signal/single-nch/rq3e100bn-product",
        "数据来源": "ROHM official product page",
        "数据状态": "官方网页",
        "校验备注": "VDS=30V, ID=21A, Rds(on)=0.0077Ω typ@10V, HSMT8",
    },
    {
        "品牌": "Toshiba",
        "型号": "SSM3K333R",
        "系列": "SSM3K333R",
        "系列说明": "Silicon N-channel MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "30",
        "额定电流": "6A",
        "DCR": "Rds(on) 28mΩ max@10V; 42mΩ max@4.5V",
        "封装代码": "SOT-23F",
        "安装方式": "SMT",
        "规格摘要": "30V N沟道 MOSFET 6A Rds(on) 28mΩ max SOT-23F",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://toshiba.semicon-storage.com/info/SSM3K333R_datasheet_en_20250220.pdf?did=6736&prodName=SSM3K333R",
        "数据来源": "Toshiba official datasheet/product page",
        "数据状态": "官方PDF",
        "校验备注": "VDSS=30V, ID=6.0A, Rds(on)=28mΩ max@10V / 42mΩ max@4.5V, SOT-23F",
    },
    {
        "品牌": "Nexperia",
        "型号": "PMV16XN",
        "系列": "PMV16XN",
        "系列说明": "20V N-channel Trench MOSFET",
        "器件类型": "MOSFET",
        "特殊用途": "N沟道 MOSFET",
        "极性": "N沟道",
        "耐压（V）": "20",
        "额定电流": "8.6A",
        "DCR": "Rds(on) 20mΩ max@4.5V; 24mΩ max@2.5V",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "20V N沟道 MOSFET 8.6A Rds(on) 20mΩ SOT-23",
        "生产状态": "Production",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.nexperia.com/product/PMV16XN",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VDS=20V, ID=8.6A, Rds(on)=20mΩ max@4.5V, SOT23",
    },
    {
        "品牌": "ROHM",
        "型号": "RB751SM-40T2R",
        "系列": "RB751SM-40",
        "系列说明": "30V 30mA SOD-523 Schottky barrier diode",
        "器件类型": "二极管",
        "特殊用途": "肖特基二极管",
        "耐压（V）": "30",
        "额定电流": "0.03A",
        "封装代码": "SOD-523",
        "安装方式": "SMT",
        "尺寸（mm）": "1.6x0.8x0.7",
        "规格摘要": "30V 30mA Schottky barrier diode SOD-523",
        "生产状态": "Recommended",
        "工作温度": "-40~150℃",
        "官网链接": "https://www.rohm.com/products/diodes/schottky-barrier-diodes/ultra-low-vf/rb751sm-40-product",
        "数据来源": "ROHM official product page",
        "数据状态": "官方网页",
        "校验备注": "VR=30V, VRM=40V, IO=30mA, VF max 0.37V, SOD-523",
    },
    {
        "品牌": "Toshiba",
        "型号": "CUS10F40",
        "系列": "CUS10F40",
        "系列说明": "Small-signal Schottky barrier diode",
        "器件类型": "二极管",
        "特殊用途": "肖特基二极管",
        "耐压（V）": "40",
        "额定电流": "1A",
        "封装代码": "SOD-323/USC",
        "安装方式": "SMT",
        "尺寸（mm）": "2.5x1.25x0.9",
        "规格摘要": "40V 1A Schottky barrier diode SOD-323/USC",
        "生产状态": "Active",
        "官网链接": "https://toshiba.semicon-storage.com/us/semiconductor/product/diodes/detail.CUS10F40.html",
        "数据来源": "Toshiba official product page",
        "数据状态": "官方网页",
        "校验备注": "VR=40V, IO=1A, package SOD-323(USC)",
    },
    {
        "品牌": "Littelfuse",
        "型号": "DSA20C60PN",
        "系列": "Schottky Low leakage",
        "系列说明": "60V 20A Schottky rectifier diode",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "60",
        "额定电流": "2x10A",
        "封装代码": "TO-220AB/TO-220FP",
        "安装方式": "THT",
        "规格摘要": "60V 2x10A Schottky rectifier diode TO-220AB/TO-220FP",
        "生产状态": "Active",
        "官网链接": "https://www.littelfuse.com/products/power-semiconductors-control-ics/power-diodes/schottky-si-sic/schottky-low-leakage/dsa20c60pn",
        "数据来源": "Littelfuse official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VRRM=60V, IFAV=2x10A, VF=0.70V, TO-220-3L ABFP",
    },
    {
        "品牌": "MCC",
        "型号": "SK34",
        "系列": "SK32-SK310",
        "系列说明": "Surface mount Schottky barrier rectifier",
        "器件类型": "二极管",
        "特殊用途": "肖特基整流二极管",
        "耐压（V）": "40",
        "额定电流": "3A",
        "封装代码": "SMC",
        "安装方式": "SMT",
        "规格摘要": "40V 3A Schottky barrier rectifier SMC",
        "生产状态": "Catalog",
        "官网链接": "https://www.mccsemi.com/pdf/MCCProductCatalog.pdf",
        "数据来源": "MCC official product catalog",
        "数据状态": "官方PDF",
        "校验备注": "SK34 catalog row: IF=3A, VRWM=40V, SMC",
    },
    {
        "品牌": "Diodes Incorporated",
        "型号": "MMBT2222A",
        "系列": "MMBT2222A",
        "系列说明": "NPN 40V 0.6A SOT23 transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN switching transistor",
        "极性": "NPN",
        "耐压（V）": "40",
        "额定电流": "0.6A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "40V 600mA NPN transistor SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.diodes.com/products/discrete-semiconductors/bipolar-transistors/transistor-bjt-master-table/part/MMBT2222A",
        "数据来源": "Diodes Incorporated official product page",
        "数据状态": "官方网页",
        "校验备注": "VCEO=40V, IC=0.6A, SOT23",
    },
    {
        "品牌": "ROHM",
        "型号": "UMT3904T106",
        "系列": "UMT3904",
        "系列说明": "NPN 40V 200mA switching transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN switching transistor",
        "极性": "NPN",
        "耐压（V）": "40",
        "额定电流": "0.2A",
        "封装代码": "SOT-323/UMT3",
        "安装方式": "SMT",
        "尺寸（mm）": "2.1x2.0x1.0",
        "规格摘要": "40V 200mA NPN switching transistor SOT-323/UMT3",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.rohm.com/products/transistors/bipolar-transistors/standard-bipolar-transistors/umt3904-product",
        "数据来源": "ROHM official product page",
        "数据状态": "官方网页",
        "校验备注": "VCEO=40V, IC=0.2A, hFE=100-300, UMT3/SOT-323",
    },
    {
        "品牌": "Toshiba",
        "型号": "2SC2712",
        "系列": "2SC2712",
        "系列说明": "Silicon NPN epitaxial transistor",
        "器件类型": "三极管",
        "特殊用途": "NPN low-frequency small-signal transistor",
        "极性": "NPN",
        "耐压（V）": "50",
        "封装代码": "S-Mini",
        "安装方式": "SMT",
        "规格摘要": "50V NPN low-frequency small-signal transistor S-Mini",
        "生产状态": "Active",
        "官网链接": "https://toshiba.semicon-storage.com/ap-en/semiconductor/product/bipolar-transistors/detail.2SC2712.html",
        "数据来源": "Toshiba official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VCEO=50V, NPN, S-Mini; current requires datasheet confirmation for final design",
    },
    {
        "品牌": "STMicroelectronics",
        "型号": "2STR2230",
        "系列": "2STR2230",
        "系列说明": "Low voltage fast-switching PNP power transistor",
        "器件类型": "三极管",
        "特殊用途": "PNP fast-switching power transistor",
        "极性": "PNP",
        "耐压（V）": "30",
        "额定电流": "1.5A",
        "封装代码": "SOT-23",
        "安装方式": "SMT",
        "规格摘要": "30V 1.5A PNP fast-switching power transistor SOT-23",
        "生产状态": "Active",
        "官网链接": "https://www.st.com/en/power-transistors/2str2230.html",
        "数据来源": "STMicroelectronics official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "PNP, VCEO=30V, IC=1.5A, SOT-23",
    },
    {
        "品牌": "Vishay",
        "型号": "SMBJ5.0CA",
        "系列": "SMBJ",
        "系列说明": "600W Surface-Mount TransZorb transient voltage suppressor",
        "器件类型": "TVS二极管",
        "特殊用途": "TVS二极管",
        "极性": "双向",
        "耐压（V）": "5",
        "封装代码": "SMB/DO-214AA",
        "安装方式": "SMT",
        "规格摘要": "600W 双向 TVS VRWM 5V SMB/DO-214AA",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/en/product/88392/",
        "数据来源": "Vishay official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "SMBJ5.0CA in SMBJ5.0A-SMBJ188A family: VRWM=5V, VBR=6.40-7.07V, VC=9.2V, 600W",
    },
    {
        "品牌": "onsemi",
        "型号": "ESD5Z5.0T1G",
        "系列": "ESD5Z",
        "系列说明": "5V ESD protection TVS diode",
        "器件类型": "TVS二极管",
        "特殊用途": "ESD/TVS保护二极管",
        "极性": "单向",
        "耐压（V）": "5",
        "封装代码": "SOD-523",
        "安装方式": "SMT",
        "规格摘要": "5V 单向 ESD/TVS保护二极管 SOD-523",
        "生产状态": "Active",
        "工作温度": "-55~150℃",
        "官网链接": "https://www.onsemi.com/PowerSolutions/availability.do?part=ESD5Z5.0T1G",
        "数据来源": "onsemi official availability page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "VRWM=5V, VBR min 6.2V, VC=18.6V, IPP=9.4A(8/20us), SOD-523",
    },
    {
        "品牌": "Nexperia",
        "型号": "PESD5V0S1BA",
        "系列": "PESD5V0S1BA",
        "系列说明": "Bidirectional ESD protection diode",
        "器件类型": "TVS二极管",
        "特殊用途": "ESD保护二极管",
        "极性": "双向",
        "耐压（V）": "5",
        "封装代码": "SOD-323/SC-76",
        "安装方式": "SMT",
        "规格摘要": "5V 双向 ESD保护二极管 SOD-323/SC-76",
        "生产状态": "Production",
        "官网链接": "https://www.nexperia.com/product/pesd5v0s1ba",
        "数据来源": "Nexperia official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "Bidirectional ESD protection diode, SOD323/SC-76, 5V class",
    },
    {
        "品牌": "STMicroelectronics",
        "型号": "ESDA6V1-5SC6Y",
        "系列": "ESDA6V1",
        "系列说明": "Automotive 5-line 5.2V TVS array",
        "器件类型": "TVS二极管",
        "特殊用途": "ESD/TVS阵列",
        "极性": "单向",
        "耐压（V）": "5.2",
        "封装代码": "SOT23-6L",
        "安装方式": "SMT",
        "尺寸（mm）": "2.9x2.8x1.18",
        "规格摘要": "5线 5.2V TVS/ESD保护阵列 SOT23-6L",
        "生产状态": "Active",
        "官网链接": "https://www.st.com/en/protections-and-emi-filters/esda6v1-5sc6y.html",
        "数据来源": "STMicroelectronics official product page/datasheet",
        "数据状态": "官方网页",
        "校验备注": "Automotive 5-line TVS, VBR min 6.1V, SOT23-6L",
    },
    {
        "品牌": "Bourns",
        "型号": "CDSOD323-T05C",
        "系列": "CDSOD323-TxxC",
        "系列说明": "Low/standard capacitance transient voltage suppressor",
        "器件类型": "TVS二极管",
        "特殊用途": "TVS二极管",
        "极性": "双向",
        "耐压（V）": "5",
        "封装代码": "SOD-323",
        "安装方式": "SMT",
        "规格摘要": "5V 双向 TVS 350W SOD-323",
        "生产状态": "Active",
        "官网链接": "https://bourns.com/products/diodes/tvs-diodes",
        "数据来源": "Bourns official TVS diode page/short-form datasheet",
        "数据状态": "官方网页",
        "校验备注": "VRWM=5V, VC=18.3V, IPP=17A(8/20us), 350W, SOD-323",
    },
]


def ensure_columns(conn):
    columns = [row[1] for row in conn.execute("PRAGMA table_info(components)").fetchall()]
    return columns


def clean_model_key(value):
    return str(value or "").upper().replace("-", "").replace(" ", "").replace("_", "")


def sync_rows(dry_run=False):
    if not os.path.exists(DB_PATH):
        raise FileNotFoundError(DB_PATH)
    conn = sqlite3.connect(DB_PATH)
    try:
        columns = ensure_columns(conn)
        now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        rows = []
        for seed in SEED_ROWS:
            row = {col: "" for col in columns}
            row.update({key: value for key, value in seed.items() if key in row})
            if "校验时间" in row:
                row["校验时间"] = now
            rows.append(row)
        if dry_run:
            return len(rows)

        for row in rows:
            conn.execute(
                "DELETE FROM components WHERE [品牌] = ? AND "
                "REPLACE(REPLACE(REPLACE(UPPER(IFNULL([型号], '')), '-', ''), ' ', ''), '_', '') = ?",
                (row.get("品牌", ""), clean_model_key(row.get("型号", ""))),
            )
        placeholders = ",".join(["?"] * len(columns))
        column_sql = ",".join(f"[{col}]" for col in columns)
        insert_sql = f"INSERT INTO components ({column_sql}) VALUES ({placeholders})"
        conn.executemany(insert_sql, [[row.get(col, "") for col in columns] for row in rows])
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Sync source-backed semiconductor seed rows into components.db")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    count = sync_rows(dry_run=args.dry_run)
    action = "would_sync" if args.dry_run else "synced"
    print(f"{action}_semiconductor_rows={count}")


if __name__ == "__main__":
    main()
