from __future__ import annotations

import argparse
import datetime as dt
import os
import sqlite3


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "components.db")


SEED_ROWS = [
    {
        "品牌": "KEMET",
        "型号": "R82DC3100AA50J",
        "系列": "R82",
        "系列说明": "Metallized polyester stacked film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "63",
        "特殊用途": "Automotive grade DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.2x2.5x6.5",
        "长度（mm）": "7.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET 薄膜电容 0.1uF ±5% 63VDC 径向 P=5.0mm 7.2x2.5x6.5mm",
        "生产状态": "Active",
        "工作温度": "-55~105℃",
        "官网链接": "https://search.kemet.com/component-documentation/download/specsheet/R82DC3100AA50J",
        "数据来源": "KEMET/YAGEO official spec sheet",
        "数据状态": "官方PDF",
        "校验备注": "R82DC3100AA50J: 0.1uF, 5%, 63VDC, metallized polyester, radial, P=5mm",
    },
    {
        "品牌": "WIMA",
        "型号": "MKS2C031001A00JSSD",
        "系列": "MKS2",
        "系列说明": "Metallized polyester film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "63",
        "特殊用途": "General DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.2x2.5x6.5",
        "长度（mm）": "7.2",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET 薄膜电容 0.1uF ±5% 63VDC WIMA MKS2 P=5.0mm",
        "生产状态": "Active",
        "工作温度": "-55~125℃",
        "官网链接": "https://www.wima.de/wp-content/uploads/media/e_WIMA_MKS_2.pdf",
        "数据来源": "WIMA official MKS2 datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MKS2C031001A00JSSD: 0.1uF row, 63VDC, J=5%, bulk S, pin length SD",
    },
    {
        "品牌": "Panasonic",
        "型号": "ECWFD2W105J",
        "系列": "ECWFD",
        "系列说明": "Metallized PP film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "450",
        "特殊用途": "Resin dipped radial leaded DC film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P15.0",
        "尺寸（mm）": "17.5x7.8x11.0",
        "长度（mm）": "17.5",
        "宽度（mm）": "7.8",
        "高度（mm）": "11.0",
        "脚距（mm）": "15.0",
        "规格摘要": "PP 薄膜电容 1uF ±5% 450VDC 径向 P=15.0mm",
        "生产状态": "Active",
        "工作温度": "-40~110℃",
        "官网链接": "https://industrial.panasonic.com/ww/products/pt/film-cap-electroequip/models/ECWFD2W105J",
        "数据来源": "Panasonic official product page",
        "数据状态": "官方网页",
        "校验备注": "ECWFD2W105J: 1uF, ±5%, 450VDC, MPP, L=17.5 T=7.8 H=11.0, P=15.0",
    },
    {
        "品牌": "TDK",
        "型号": "B32529C0104K000",
        "系列": "B32529",
        "系列说明": "MKT general purpose film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "63",
        "特殊用途": "RFI filtering / smoothing / general purpose",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.3x2.5x6.5",
        "长度（mm）": "7.3",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET/MKT 薄膜电容 0.1uF ±10% 63VDC TDK B32529 P=5.0mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/en/search/capacitor/film/rfi_general/info?part_no=B32529C0104K000",
        "数据来源": "TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "B32529C0104K000: 100nF ±10%, 63VDC, polyester, 7.3x2.5x6.5mm, P=5mm",
    },
    {
        "品牌": "Epcos",
        "型号": "B32529C0104K000",
        "系列": "B32529",
        "系列说明": "EPCOS/TDK MKT general purpose film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "63",
        "特殊用途": "RFI filtering / smoothing / general purpose",
        "安装方式": "插件",
        "封装代码": "RADIAL/P5.0",
        "尺寸（mm）": "7.3x2.5x6.5",
        "长度（mm）": "7.3",
        "宽度（mm）": "2.5",
        "高度（mm）": "6.5",
        "脚距（mm）": "5.0",
        "规格摘要": "PET/MKT 薄膜电容 0.1uF ±10% 63VDC EPCOS/TDK B32529 P=5.0mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/ja/search/capacitor/film/rfi_general/info?part_no=B32529C0104K000",
        "数据来源": "EPCOS/TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "EPCOS brand alias for B32529C0104K000 in TDK Product Center",
    },
    {
        "品牌": "Vishay",
        "型号": "MKP1848C51060JK2",
        "系列": "MKP1848C",
        "系列说明": "DC-link metallized polypropylene film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "1",
        "容值单位": "UF",
        "容值误差": "5",
        "耐压（V）": "600",
        "特殊用途": "DC-link / high ripple current film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P27.5",
        "尺寸（mm）": "32x9x19",
        "长度（mm）": "32",
        "宽度（mm）": "9",
        "高度（mm）": "19",
        "脚距（mm）": "27.5",
        "规格摘要": "PP 薄膜电容 1uF ±5% 600VDC Vishay MKP1848C P=27.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/doc?26015=",
        "数据来源": "Vishay official MKP1848C datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MKP1848C51060JK2: 600VDC, 1uF, height 19mm, PP, radial",
    },
    {
        "品牌": "CDE",
        "型号": "940C30P1K-F",
        "系列": "940C",
        "系列说明": "High dV/dt metallized polypropylene axial film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PP",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "3000",
        "特殊用途": "High pulse / high dV/dt snubber film capacitor",
        "安装方式": "插件",
        "封装代码": "AXIAL",
        "尺寸（mm）": "Ø22.5x46",
        "长度（mm）": "46",
        "直径（mm）": "22.5",
        "规格摘要": "PP 薄膜电容 0.1uF ±10% 3000VDC 轴向 940C",
        "生产状态": "Active",
        "工作温度": "-55~105℃",
        "官网链接": "https://www.cde.com/resources/catalogs/940C.pdf",
        "数据来源": "Cornell Dubilier / CDE official 940C datasheet",
        "数据状态": "官方PDF",
        "校验备注": "940C30P1K-F: 0.1uF, ±10%, 3000VDC, PP metallized, axial",
    },
    {
        "品牌": "Nichicon",
        "型号": "QYX2A104KTP",
        "系列": "QYX",
        "系列说明": "Foil type polyester film capacitor",
        "器件类型": "薄膜电容",
        "材质（介质）": "PET",
        "容值": "0.1",
        "容值单位": "UF",
        "容值误差": "10",
        "耐压（V）": "100",
        "特殊用途": "General purpose polyester film capacitor",
        "安装方式": "插件",
        "封装代码": "RADIAL/P7.5",
        "尺寸（mm）": "11.0x5.5x14.0",
        "长度（mm）": "11.0",
        "宽度（mm）": "5.5",
        "高度（mm）": "14.0",
        "脚距（mm）": "7.5",
        "规格摘要": "PET 薄膜电容 0.1uF ±10% 100VDC Nichicon QYX P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.nichicon.co.jp/english/series_items/catalog_pdf/e-qyx.pdf",
        "数据来源": "Nichicon official QYX datasheet",
        "数据状态": "官方PDF",
        "校验备注": "QYX2A104KTP: 0.1uF, ±10%, 100VDC, T=5.5 W=11.0 H=14.0, P=7.5",
    },
    {
        "品牌": "TDK",
        "型号": "B72214S0271K101",
        "系列": "S14K275",
        "系列说明": "Leaded disk metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D431K, 275VAC, 350VDC, Vv=430V, Imax=4.5kA",
        "规格摘要": "TDK S14K275 14D431K 引线型压敏电阻 430V ±10% 275VAC P=7.5mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/en/search/protection/voltage/lead-disk-varistor/info?part_no=B72214S0271K101",
        "数据来源": "TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "S14K275: 275VAC, 350VDC, Vv=430V class, 14mm disk, P=7.5mm",
    },
    {
        "品牌": "Epcos",
        "型号": "B72214S0271K101",
        "系列": "S14K275",
        "系列说明": "EPCOS leaded disk metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D431K, 275VAC, 350VDC, Vv=430V, Imax=4.5kA",
        "规格摘要": "EPCOS S14K275 14D431K 引线型压敏电阻 430V ±10% 275VAC P=7.5mm",
        "生产状态": "Production",
        "官网链接": "https://product.tdk.com/ja/search/protection/voltage/lead-disk-varistor/info?part_no=B72214S0271K101",
        "数据来源": "EPCOS/TDK official product page",
        "数据状态": "官方网页",
        "校验备注": "EPCOS brand alias for B72214S0271K101 / S14K275",
    },
    {
        "品牌": "Bourns",
        "型号": "MOV-14D471K",
        "系列": "MOV-14D",
        "系列说明": "Metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA, 125J",
        "规格摘要": "Bourns MOV-14D471K 引线型压敏电阻 470V ±10% 300VAC P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.bourns.com/data/global/pdfs/MOV14D.pdf",
        "数据来源": "Bourns official MOV-14D datasheet",
        "数据状态": "官方PDF",
        "校验备注": "MOV-14D471K: Vv=470V, 300VAC, 385VDC, Vc=775V, Imax=4.5kA, 14mm disk",
    },
    {
        "品牌": "Littelfuse",
        "型号": "V14E275P",
        "系列": "UltraMOV",
        "系列说明": "UltraMOV radial leaded varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "430",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "备注1": "14D431K, 275VAC, 350VDC, V_NDC=387-473V, Vc=710V, Imax=6kA",
        "规格摘要": "Littelfuse V14E275P 14D431K 引线型压敏电阻 430V级 275VAC",
        "生产状态": "Active",
        "官网链接": "https://www.littelfuse.com/products/overvoltage-protection/varistors/radial-leaded-varistors/ultramov/v14e275p",
        "数据来源": "Littelfuse official product page",
        "数据状态": "官方网页",
        "校验备注": "V14E275P: 275VAC, 350VDC, V_NDC 387-473V, Vc=710V, 14mm radial",
    },
    {
        "品牌": "Panasonic",
        "型号": "ERZV14D471",
        "系列": "ERZV",
        "系列说明": "ZNR surge absorber varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / ZNR",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=6kA, 125J",
        "规格摘要": "Panasonic ERZV14D471 14D471K 引线型压敏电阻 470V ±10% P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://industrial.panasonic.com/ww/products/pt/surge-components/models/ERZV14D471",
        "数据来源": "Panasonic official product page",
        "数据状态": "官方网页",
        "校验备注": "ERZV14D471: varistor voltage 470V, range 423-517V, 300VAC, 385VDC, 14 series",
    },
    {
        "品牌": "Vishay",
        "型号": "VDRS14T300BSE",
        "系列": "VDRS",
        "系列说明": "Through-hole metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA",
        "规格摘要": "Vishay VDRS14T300BSE 14D471K 引线型压敏电阻 470V级 300VAC",
        "生产状态": "Active",
        "官网链接": "https://www.vishay.com/docs/29081/vdrs.pdf",
        "数据来源": "Vishay official VDRS datasheet",
        "数据状态": "官方PDF",
        "校验备注": "VDRS14T300 series: 300VAC, 385VDC, Vv=470V, Vc=775V, 14mm disk class",
    },
    {
        "品牌": "Joyin",
        "型号": "JVR14N471K87PU5",
        "系列": "JVR",
        "系列说明": "Metal oxide varistor",
        "器件类型": "引线型压敏电阻",
        "容值误差": "10",
        "耐压（V）": "470",
        "特殊用途": "压敏电阻 / MOV",
        "安装方式": "插件",
        "封装代码": "14D/P7.5",
        "尺寸（mm）": "14D",
        "直径（mm）": "14",
        "脚距（mm）": "7.5",
        "备注1": "14D471K, 300VAC, 385VDC, Vv=470V, Vc=775V, Imax=4.5kA, 140J",
        "规格摘要": "Joyin JVR14N471K87PU5 14D471K 引线型压敏电阻 470V ±10% P=7.5mm",
        "生产状态": "Active",
        "官网链接": "https://www.joyin.com.tw/storage/system/product/pdf/MOV_JVR_datasheet20250305.pdf",
        "数据来源": "Joyin official JVR datasheet",
        "数据状态": "官方PDF",
        "校验备注": "JVR14N471K: Vv=470V, 300VAC, 385VDC, Vc=775V, Imax=4.5kA, energy 140J",
    },
]


def ensure_columns(conn):
    return [row[1] for row in conn.execute("PRAGMA table_info(components)").fetchall()]


def clean_model_key(value):
    return str(value or "").upper().replace("-", "").replace(" ", "").replace("_", "")


def sync_rows(dry_run=False):
    if not os.path.exists(DB_PATH):
        raise FileNotFoundError(DB_PATH)
    conn = sqlite3.connect(DB_PATH)
    try:
        columns = ensure_columns(conn)
        now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        rows = []
        for seed in SEED_ROWS:
            row = {col: "" for col in columns}
            row.update({key: value for key, value in seed.items() if key in row})
            if "校验时间" in row:
                row["校验时间"] = now
            rows.append(row)
        if dry_run:
            return len(rows)

        for row in rows:
            conn.execute(
                "DELETE FROM components WHERE [品牌] = ? AND "
                "REPLACE(REPLACE(REPLACE(UPPER(IFNULL([型号], '')), '-', ''), ' ', ''), '_', '') = ?",
                (row.get("品牌", ""), clean_model_key(row.get("型号", ""))),
            )
        placeholders = ",".join(["?"] * len(columns))
        column_sql = ",".join(f"[{col}]" for col in columns)
        insert_sql = f"INSERT INTO components ({column_sql}) VALUES ({placeholders})"
        conn.executemany(insert_sql, [[row.get(col, "") for col in columns] for row in rows])
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Sync source-backed passive gap seed rows into components.db")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    count = sync_rows(dry_run=args.dry_run)
    action = "would_sync" if args.dry_run else "synced"
    print(f"{action}_passive_gap_rows={count}")


if __name__ == "__main__":
    main()
