(function(){
 'use strict';
 const P=window.TrainingPractice,L=window.TrainingLesson,$=id=>document.getElementById(id),key='fruition_training_practice_v1';
 const names={resistor:'贴片电阻',capacitor:'陶瓷电容',inductor:'电感',diode:'二极管'};
 const quizzes=L.quizzes(),bank=[...P.scenarios,...Object.entries(quizzes).map(([course,q])=>({...q,id:'quiz-'+course,course,title:names[course]+' · 课堂小测验'}))];
 let records={},storageOK=true,scenario=P.scenarios[0].id;
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 try{records=P.validRecords(JSON.parse(localStorage.getItem(key)||'{}'));}catch(_){storageOK=false;}
 // Recompute correctness from current question data, never trust stored grading.
 for(const [id,r] of Object.entries(records)){const q=bank.find(x=>x.id===id);if(q)r.correct=P.grade(q,r.choice);}
 function storageMessage(){const message=$('practice-storage');message.hidden=storageOK;message.textContent=storageOK?'':'练习记录暂时无法保存，刷新后请重新练习。';}
 function persist(){try{localStorage.setItem(key,JSON.stringify(records));storageOK=true;}catch(_){storageOK=false;}storageMessage();}
 function sync(){const progress={};for(const c of Object.keys(quizzes))progress[c]=records['quiz-'+c]?.correct===true;L.setQuizProgress(progress);}
 function record(id,choice){const q=bank.find(x=>x.id===id);if(!q)return;records[id]={choice,correct:P.grade(q,choice),attempts:Math.min(10000,(records[id]?.attempts||0)+1)};persist();sync();renderMistakes();}
 function toolTab(name,focus=false){document.querySelectorAll('[data-tool]').forEach(b=>{const on=b.dataset.tool===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;if(on&&focus)b.focus();});document.querySelectorAll('.tool-panel').forEach(n=>n.hidden=n.id!=='tool-panel-'+name);}
 document.querySelectorAll('[data-tool]').forEach(b=>{b.addEventListener('click',()=>toolTab(b.dataset.tool));b.addEventListener('keydown',e=>{const all=['decode','scenario','mistakes'];let next;if(e.key==='ArrowRight'||e.key==='ArrowLeft')next=all[(all.indexOf(b.dataset.tool)+(e.key==='ArrowRight'?1:2))%3];if(e.key==='Home')next=all[0];if(e.key==='End')next=all[2];if(next){e.preventDefault();toolTab(next,true);}});});
 function showDecode(){const r=P.decode($('decode-input').value),out=$('decode-result');out.replaceChildren();const status=node('p',r.message,'decode-status '+r.status);out.append(status);if(r.model)out.append(node('h3',r.model,'decoded-model'));if(r.fields.length){const list=node('dl',undefined,'decode-fields');for(const f of r.fields){const wrap=node('div');wrap.append(node('dt',f.code+' · '+f.label),node('dd',f.value));list.append(wrap);}out.append(list);}for(const [label,url] of r.sources){const a=node('a',label+' ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';out.append(a);}}
 $('decode-form').addEventListener('submit',e=>{e.preventDefault();showDecode();});
 for(const example of P.examples){const b=node('button',example);b.type='button';b.addEventListener('click',()=>{$('decode-input').value=example;showDecode();});$('decode-examples').append(b);}
 for(const q of bank){const option=node('option',q.title);option.value=q.id;$('scenario-select').append(option);}
 function renderQuestion(q){const out=$('scenario-question');out.replaceChildren(node('h3',q.title),node('p',q.question,'scenario-prompt'));const form=node('form'),fieldset=node('fieldset');fieldset.append(node('legend','选择最符合题设的处理方式'));q.options.forEach((text,i)=>{const label=node('label',undefined,'scenario-option'),input=node('input');input.type='radio';input.name='practice-choice';input.value=String(i);input.required=true;label.append(input,node('span',String.fromCharCode(65+i)+' · '+text));fieldset.append(label);});const submit=node('button','提交并查看解析','primary');submit.type='submit';const feedback=node('div',undefined,'practice-feedback');feedback.setAttribute('aria-live','polite');form.append(fieldset,submit,feedback);form.addEventListener('submit',e=>{e.preventDefault();const checked=form.querySelector('input:checked');if(!checked){feedback.textContent='请先选择一个选项。';return;}const choice=Number(checked.value),correct=P.grade(q,choice);record(q.id,choice);feedback.replaceChildren(node('strong',correct?'回答正确 · 满足本题条件':'暂未答对 · 已收录错题本'),node('p',q.why?q.why[choice]:q.explain),node('p',q.explain),node('p','向客户推荐替代型号前，还要核对完整规格和使用条件。','storage-note'));feedback.className='practice-feedback '+(correct?'correct':'incorrect');const next=node('button','下一题');next.type='button';next.addEventListener('click',()=>{scenario=bank[(bank.findIndex(x=>x.id===q.id)+1)%bank.length].id;$('scenario-select').value=scenario;renderQuestion(bank.find(x=>x.id===scenario));});feedback.append(next);});out.append(form);}
 $('scenario-select').addEventListener('change',()=>{scenario=$('scenario-select').value;renderQuestion(bank.find(q=>q.id===scenario));});
 function renderMistakes(){const wrong=bank.filter(q=>records[q.id]&&!records[q.id].correct),done=bank.filter(q=>records[q.id]?.correct).length;$('mistake-count').textContent=String(wrong.length);$('practice-progress').textContent='已答对 '+done+' / '+bank.length+' 题';const out=$('mistake-list');out.replaceChildren();if(!wrong.length)out.append(node('p','目前没有待复习错题。可以先做选型实战，或完成上方课堂小测验。','empty-mistakes'));for(const q of wrong){const card=node('article',undefined,'mistake-item');card.append(node('h3',q.title),node('p',q.question),node('p','上次选择：'+q.options[records[q.id].choice]));const details=node('details'),summary=node('summary','查看解析');details.append(summary,node('p','正确选择：'+q.options[q.answer]),node('p',q.explain));const retry=node('button','重新练习');retry.type='button';retry.dataset.retry=q.id;retry.addEventListener('click',()=>{scenario=q.id;$('scenario-select').value=scenario;renderQuestion(q);toolTab('scenario',true);});card.append(details,retry);out.append(card);} $('clear-practice').disabled=Object.keys(records).length===0;}
 // Existing lesson quiz remains the source of truth for wording/answer keys.
 $('panel-quiz').addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(b){const id='quiz-'+L.current().course;record(id,Number(b.dataset.answer));}});
 $('clear-practice').addEventListener('click',()=>{$('clear-confirm').hidden=false;$('confirm-clear').focus();});
 $('cancel-clear').addEventListener('click',()=>{$('clear-confirm').hidden=true;$('clear-practice').focus();});
 $('confirm-clear').addEventListener('click',()=>{records={};persist();sync();L.refreshQuiz();renderMistakes();renderQuestion(bank.find(q=>q.id===scenario));$('clear-confirm').hidden=true;$('tool-mistakes').focus();});
 window.addEventListener('storage',e=>{if(e.key!==key&&e.key!==null)return;try{records=P.validRecords(JSON.parse(localStorage.getItem(key)||'{}'));for(const [id,r] of Object.entries(records))r.correct=P.grade(bank.find(q=>q.id===id),r.choice);storageOK=true;}catch(_){storageOK=false;}sync();renderMistakes();storageMessage();});
 sync();renderMistakes();renderQuestion(bank[0]);storageMessage();
})();
