(function(){
 'use strict';
 const M=window.TrainingMath,$=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const icons={resistor:'<path d="M3 17h6l3-7 5 14 5-14 5 14 3-7h7"/>',capacitor:'<path d="M3 17h12m0-10v20m8-20v20m0-10h12"/>',inductor:'<path d="M2 21h5c0-15 7-15 7 0 0-15 7-15 7 0 0-15 7-15 7 0h7"/>',diode:'<path d="M2 17h9m0-10 14 10-14 10V7m14 0v20m0-10h11"/>'};
 const courses={
  resistor:{title:'贴片电阻',english:'Chip Resistor',summary:'限流 · 分压 · 功耗',model:'厚膜贴片电阻',parts:[['substrate','陶瓷基板','承载电阻膜并提供绝缘和机械支撑。散热同时依赖端子、焊盘与PCB，不能把颜色变化当成实际温度。'],['film','电阻膜','电阻材料使电流产生能量损耗；有效长度、截面积和材料共同决定阻值。实际厚膜与薄膜工艺不同。'],['cover','保护层','覆盖电阻膜，保护其免受环境与加工影响。展开的上盖仅用于教学，不代表可拆卸零件。'],['terminal','端电极','将电阻膜与焊盘连接。端电极和焊接结构也影响可靠性与热传递。']],
   specs:[['阻值','1 kΩ（课堂初始值）','R、kΩ、MΩ都表示电阻；mΩ表示毫欧，不是MΩ。'],['精度','例：±1% / ±5%','初始阻值误差；与温度引起的阻值漂移不是同一指标。'],['封装','例：英制0603 / 公制1608','注意编码体系，不可把英制0603直接当成公制0603。'],['额定功率','课堂默认0.125 W','须结合环境温度、焊盘及数据手册的降额条件。'],['工作电压','看功率限制和电压上限','允许值要同时满足√(P×R)和该料号最高工作电压。'],['TCR','ppm/K（或ppm/°C）','温度系数；误差、TCR和长期漂移应分别检查。']],
   formula:'I = V / R　　P = V² / R = I²R',assumption:'理想欧姆模型；功耗占比只对课堂额定功率计算，不估计实际温升、脉冲能力或降额后的安全范围。',
   steps:[['从结构理解阻值','电流经过电阻材料。材料、几何尺寸和修调共同决定阻值。'],['把电压变成电流','固定R时，电压越大，I=V/R越大；改变R也会改变电流。'],['检查平方关系','电压翻倍时，同一R的功耗变为四倍，而不是两倍。'],['回到真实选型','确认封装、精度、TCR、工作电压、脉冲能力和温度降额，不能只看阻值。']],
   tips:[['不能只看阻值','相同阻值和封装也可能有不同功率、TCR及抗脉冲能力。'],['额定值有条件','高温下通常需要降额；焊盘与PCB散热会影响使用条件。'],['0Ω不是理想导线','0Ω跳线仍有电阻和电流限制，不宜套用R=0的除法。']],
   example:'系列参考：Vishay D/CRCW e3。CRCW0603的标准与扩展运行模式分别列出0.10 W与0.125 W等条件，应连同稳定性要求阅读，不能只取较大的数字。课堂模型不是该系列的厂家仿真模型。',sources:[['Vishay · D/CRCW e3 数据手册','https://www.vishay.com/docs/20035/dcrcwe3.pdf']],
   quiz:{question:'同一个理想电阻，施加电压从5 V升到10 V，功耗变为多少？',options:['原来的2倍','原来的4倍','保持不变'],answer:1,explain:'P=V²/R。R不变时，电压翻倍，功耗变为4倍。真实使用还需检查额定值与降额条件。'},defaults:{r:1000,v:5,rating:.125}},
  capacitor:{title:'陶瓷电容',english:'Multilayer Ceramic Capacitor',summary:'储能 · 去耦 · 滤波',model:'多层陶瓷电容（MLCC）',parts:[['dielectric','陶瓷介质','电极之间的绝缘介质。不同材料决定温度、偏压与损耗特性；不能把电场动画理解成直流穿过介质。'],['electrode','内部电极','相邻电极交替连接两端。多层结构增加有效电极面积；图中层数与厚度仅为示意。'],['terminal','端电极','将交替的内部电极组引到外部两个端子。MLCC通常无极性，但仍有额定电压限制。']],
   specs:[['容量','100 nF = 0.1 µF（初始值）','注意pF、nF、µF；名义容量不一定等于工作条件下有效容量。'],['介质类别','C0G / X7R / X5R等','高介电常数材料可能有明显的DC偏压影响；C0G通常更稳定。'],['额定电压','课堂参考16 V','工作电压应满足具体料号条件，不能由封装推断耐压。'],['容量误差','例：±5% / ±10% / ±20%','误差与温度特性、偏压变化是不同因素。'],['封装','例：英制0603 / 公制1608','尺寸、容量和耐压往往需要综合权衡。'],['寄生参数','ESR / ESL / 自谐振频率','高频时不能只使用理想容抗；查看具体阻抗曲线。']],
   formula:'Q = CV　　E = ½CV²　　|Xc| = 1 / (2πfC)',assumption:'使用名义容量的理想电容模型，不含DC偏压、温度变化、ESR和ESL；不生成虚构的厂家有效容量曲线。',
   steps:[['交替连接电极','两组内部电极之间隔着陶瓷介质，形成多层储能结构。'],['建立电场','外加电压使电极积累等量异号电荷，介质中形成电场并储存能量。'],['理解频率响应','理想容抗随频率升高而降低。稳态直流与交流响应要分开理解。'],['检查非理想因素','实际器件存在漏电、ESR和ESL；X7R/X5R等还需确认DC偏压下的有效容量。']],
   tips:[['不是所有电容都一样','C0G和高介电常数材料的温度与偏压表现不同。'],['100nF≠任何条件都100nF','容量误差、偏压和温度变化需分别核对。'],['高频不能无限理想化','接近或超过自谐振频率时，应读真实阻抗曲线。']],
   example:'系列参考：Murata GRM类MLCC。厂家资料解释多层电极与介质结构，以及高介电常数材料的DC偏压效应；具体容量保持率必须查看相应料号曲线。模型不对应某个GRM料号。',sources:[['Murata · MLCC结构与材料','https://www.murata.com/support/faqs/capacitor/ceramiccapacitor/conf/0001'],['Murata · DC偏压与有效容量','https://www.murata.com/support/faqs/capacitor/ceramiccapacitor/char/0005']],
   quiz:{question:'一颗X7R电容标称10 µF，能否保证所有直流工作电压下都是10 µF？',options:['能，标称容量就是工作容量','不能，还要检查该料号的偏压及温度等特性','只看封装大小就能判断'],answer:1,explain:'名义容量有规定的测量条件。高介电常数MLCC可能随直流偏压发生有效容量变化，必须查该料号曲线。'},defaults:{c:1e-7,f:1000,v:5}},
  inductor:{title:'电感',english:'Power Inductor',summary:'磁场储能 · 电流变化',model:'绕线功率电感',parts:[['core','磁芯','引导磁通，材料与结构影响电感量和损耗。饱和后电感量可能下降；本课堂不推算实际饱和曲线。'],['winding','铜绕组','电流通过绕组建立磁场。绕组存在直流电阻，产生I²×DCR铜损。'],['cover','外封装 / 屏蔽结构','保护绕组与磁芯。不同系列采用不同屏蔽、成型或叠层方式；当前展示绕线结构。'],['terminal','端子','连接外部电路与绕组。额定电流、温升及PCB条件需要共同确认。']],
   specs:[['电感量','10 µH（课堂初始值）','确认误差和测量频率；L会受到频率、温度和电流影响。'],['饱和电流 Isat','课堂阈值2 A','定义通常对应规定的电感跌落幅度，不等于损坏电流。'],['温升电流 Irms','需看温升条件','主要与热效应有关，不能和Isat互相替代。'],['直流电阻 DCR','课堂参考0.1 Ω','决定直流铜损；实际交流和磁芯损耗未由DCR覆盖。'],['自谐振频率 SRF','以具体料号为准','寄生电容限制高频表现，不能无限外推理想感抗。'],['封装与屏蔽','核对尺寸、高度和结构','绕线、叠层、薄膜或一体成型结构不应混为一谈。']],
   formula:'V = L · di/dt　　E = ½LI²　　|Xl| = 2πfL',assumption:'固定名义L与课堂DCR的理想模型，未计磁芯/交流损耗。超过课堂Isat只提示模型失效，不虚构实际L跌落幅度。',
   steps:[['电流建立磁场','绕组电流与磁芯共同形成磁场；能量与L和I²有关。'],['反对电流突变','电感上的电压与电流变化率相关，并非“任何电流都被阻断”。'],['区分两种电流指标','Isat关注电感下降，Irms关注规定条件下温升；限制原因不同。'],['联系实际波形','选型还要考虑峰值/有效值电流、频率、纹波及损耗，并看具体器件曲线。']],
   tips:[['Isat≠Irms','二者的测量条件和性能限制不同，要分别确认。'],['先看峰值再看平均','脉动电流的峰值可能触及饱和条件，即使平均值较低。'],['感抗公式有适用范围','接近SRF或发生饱和时，理想名义L模型不能继续代替真实曲线。']],
   example:'厂家资料参考：Coilcraft电感规格及电流额定值指南。Isat的电感下降判据因系列而异，Irms也与温升条件有关。当前2 A与0.1 Ω均为课堂参数，不属于任何指定型号。',sources:[['Coilcraft · 电感规格入门','https://www.coilcraft.com/en-us/resources/application-notes/getting-started-an-introduction-to-inductor-specif/'],['Coilcraft · 电流与温度额定值','https://www.coilcraft.com/en-us/resources/application-notes/current-and-temperature-ratings/']],
   quiz:{question:'Isat和Irms是否是同一个额定电流？',options:['是，只是不同厂家叫法','不是，前者关注电感下降，后者关注温升','两者都表示瞬间烧毁的电流'],answer:1,explain:'Isat对应规定幅度的电感下降；Irms对应规定测试条件下的温升。要分别阅读定义，不能直接互换。'},defaults:{l:1e-5,i:1,f:1000,dcr:.1,isat:2}},
  diode:{title:'二极管',english:'PN Junction Diode',summary:'单向导电 · 偏置',model:'PN结与玻璃封装二极管',parts:[['p','P区 / 阳极A','P型区以空穴为多数载流子。正向偏置时，阳极电位高于阴极；动画箭头表示约定电流，不是电子运动方向。'],['junction','PN结 / 耗尽区','结区形成内建电场。正向偏置减小势垒，反向偏置增大势垒；图中区域宽度是定性示意。'],['n','N区 / 阴极K','N型区以电子为多数载流子。约定正向电流由A到K，电子的净运动方向不应与此混淆。'],['cover','玻璃封装与极性标记','当前外形为轴向玻璃封装示意。黑色环表示阴极侧；贴片封装的标记应查具体数据手册。'],['terminal','引脚','连接阳极和阴极，实际封装热阻和安装条件会影响可允许的功耗。']],
   specs:[['正向压降 Vf','必须带上If与温度条件','不是固定的0.7 V开关；随电流、温度和类型变化。'],['反向耐压','区分VR、VRRM等定义','不能由Vf或外观推断反向额定值。'],['正向电流 If','核对连续 / 峰值 / 浪涌','不同时间条件下的电流限制不可混用。'],['反向漏电 Ir','注意电压与温度条件','反向偏置不代表真实器件绝对没有电流。'],['反向恢复 trr','与开关应用有关','快恢复、肖特基等类型各有特性，不能只比较Vf。'],['极性与封装','A=阳极，K=阴极','1N4148示例为DO-35玻璃封装；当前模型不保证尺寸比例。']],
   formula:'I = Is · [exp(V / (nVt)) − 1]',assumption:'示例Shockley模型：Is=1 nA，n=2，Vt=25.85 mV（约25°C）。不含串联电阻、击穿和自热，不是1N4148厂家I–V曲线；“原理动画”箭头表示约定电流。',
   steps:[['PN结形成内建电场','P区和N区结合后形成耗尽区及势垒；掺杂示意不等于具体芯片工艺。'],['施加正向偏置','A对K为正时，势垒降低，电流随偏置增加，不是到某个固定电压才突然打开。'],['施加反向偏置','势垒增大，通常仅有小漏电；超过真实额定条件可能进入击穿，本模型不模拟击穿。'],['读数据手册条件','比较Vf时必须带上If与温度，还要确认反向耐压、电流额定值及反向恢复。']],
   tips:[['0.7V不是通用门槛','正向压降随电流、温度和二极管类型变化。'],['反向不是绝对零电流','检查漏电条件与额定反向电压，不能只看理想符号。'],['符号与极性要核对','约定正向电流由A到K，封装标记应查具体料号资料。']],
   example:'真实料号阅读示例：Nexperia公开的1N4148/1N4448数据手册。1N4148在If=10 mA条件下列出Vf最大1 V；这不是“所有电流下固定1 V”。课堂I–V计算不拟合这份数据手册。',sources:[['Nexperia · 1N4148 / 1N4448 数据手册','https://assets.nexperia.com/documents/data-sheet/1N4148_1N4448.pdf']],
   quiz:{question:'“硅二极管压降永远是0.7 V”正确吗？',options:['正确，任何工作条件都一样','不正确，必须看电流、温度与具体器件条件','压降只由封装大小决定'],answer:1,explain:'Vf不是常数。例如数据手册会在指定If和温度下给出典型或最大值，不能忽略这些条件。'},defaults:{v:.6,is:1e-9,n:2,vt:.02585}}
 };
 let active='resistor',tab='spec',params={...courses.resistor.defaults},part='substrate';
 let yaw=.55,pitch=-.4,zoom=1,explosion=0,auto=false,animation=!matchMedia('(prefers-reduced-motion: reduce)').matches,dirty=true,time=0;
 let answers={};try{const saved=JSON.parse(sessionStorage.getItem('fruition_training_answers_v1')||'{}');for(const key of Object.keys(courses))answers[key]=saved[key]===true;}catch(_){}
 const svgIcon=key=>'<svg class="course-icon" viewBox="0 0 38 34" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'+icons[key]+'</svg>';
 function courseButtons(){ $('courses').innerHTML=Object.entries(courses).map(([key,c])=>'<button type="button" class="course" data-course="'+key+'" aria-pressed="'+(active===key)+'">'+svgIcon(key)+'<span><strong>'+c.title+'</strong><small>'+(answers[key]?'已答对 · ':c.summary+' · ')+c.english+'</small></span></button>').join('');document.querySelectorAll('button[data-course]').forEach(b=>b.addEventListener('click',()=>switchCourse(b.dataset.course)));const done=Object.values(answers).filter(Boolean).length;document.querySelector('.lesson-count').textContent=done?'小测验已完成 '+done+' / 4':'4 类器件 · 交互课堂'; }
 function selectPart(id){if(!courses[active].parts.some(p=>p[0]===id))return;part=id;const p=courses[active].parts.find(p=>p[0]===id);$('part-detail').innerHTML='<strong></strong><span></span>';$('part-detail').querySelector('strong').textContent=p[1];$('part-detail').querySelector('span').textContent=p[2];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===id)));dirty=true;}
 function renderCourse(){const c=courses[active];$('model-title').textContent=c.model;$('parts').innerHTML=c.parts.map((p,i)=>'<button type="button" data-part="'+p[0]+'" aria-pressed="false">'+(i+1)+' · '+p[1]+'</button>').join('');document.querySelectorAll('[data-part]').forEach(b=>b.addEventListener('click',()=>selectPart(b.dataset.part)));selectPart(part);$('panel-spec').innerHTML='<h3>先读懂关键规格</h3><p class="lead">以下为通用参数说明和课堂初始值，不是具体料号的完整规格。</p><table class="spec-table"><tbody>'+c.specs.map(r=>'<tr><th scope="row">'+r[0]+'</th><td><strong>'+r[1]+'</strong><small>'+r[2]+'</small></td></tr>').join('')+'</tbody></table><div class="info">下一步：点击“电气性能”调参数，计算结果会同时改变模型中的原理示意。</div>';$('panel-principle').innerHTML='<h3>把结构与行为联系起来</h3><div class="formula">'+c.formula+'</div><ol class="steps">'+c.steps.map(s=>'<li><strong>'+s[0]+'</strong><span>'+s[1]+'</span></li>').join('')+'</ol><div class="info">'+c.assumption+'</div>';$('takeaways').innerHTML=c.tips.map(t=>'<p><strong>'+t[0]+'</strong>'+t[1]+'</p>').join('');$('example').textContent=c.example;$('sources').innerHTML=c.sources.map(s=>'<a target="_blank" rel="noopener noreferrer" href="'+s[1]+'">'+s[0]+' ↗</a>').join('');renderPerformance();renderQuiz();setTab(tab);courseButtons();dirty=true;}
 function switchCourse(key){if(!courses[key])return;active=key;params={...courses[key].defaults};part=courses[key].parts[0][0];explosion=0;$('explode').value='0';$('explode-value').value='0%';yaw=.55;pitch=-.4;zoom=1;renderCourse();}
 function setTab(key,focus=false){tab=key;document.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===key;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;if(selected&&focus)b.focus();});document.querySelectorAll('[role="tabpanel"]').forEach(p=>p.hidden=p.id!=='panel-'+key);}
 document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>setTab(b.dataset.tab));b.addEventListener('keydown',e=>{const tabs=['spec','performance','principle','quiz'];let i=tabs.indexOf(tab);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();setTab(tabs[(i+(e.key==='ArrowRight'?1:3))%4],true);}if(e.key==='Home'||e.key==='End'){e.preventDefault();setTab(tabs[e.key==='Home'?0:3],true);}});});
 function control(key,label,min,max,value,step,log=false,unit=''){return '<label class="control"><span class="control-label"><span>'+label+'</span><output id="out-'+key+'"></output></span><input aria-label="'+label+'" data-param="'+key+'" data-log="'+log+'" data-unit="'+unit+'" type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+value+'"></label>';}
 function renderPerformance(){let controls='';if(active==='resistor')controls=control('r','阻值 R',1,5,Math.log10(params.r),.1,true,'Ω')+control('v','电压 V',0,20,params.v,.1,false,'V')+'<label class="control"><span class="control-label">课堂额定功率</span><select aria-label="课堂额定功率" data-param="rating"><option value="0.063">0.063 W</option><option value="0.125" selected>0.125 W</option><option value="0.25">0.25 W</option><option value="0.5">0.5 W</option></select></label>';if(active==='capacitor')controls=control('c','名义容量 C',-9,-4,Math.log10(params.c),.1,true,'F')+control('f','频率 f',1,6,Math.log10(params.f),.1,true,'Hz')+control('v','电压 V',0,20,params.v,.1,false,'V');if(active==='inductor')controls=control('l','名义电感 L',-6,-3,Math.log10(params.l),.1,true,'H')+control('i','电流 I',0,5,params.i,.05,false,'A')+control('f','频率 f',1,6,Math.log10(params.f),.1,true,'Hz');if(active==='diode')controls=control('v','结偏置 V（A对K）',-2,.95,params.v,.01,false,'V');const c=courses[active];$('panel-performance').innerHTML='<h3>参数实验 · '+c.title+'</h3><div class="controls">'+controls+'</div><div id="metrics" class="metrics"></div><div id="lab-status" class="status" role="status"></div><div id="plot"></div><p class="math-warning">'+c.assumption+'</p>';document.querySelectorAll('[data-param]').forEach(input=>input.addEventListener('input',()=>{params[input.dataset.param]=input.dataset.log==='true'?10**Number(input.value):Number(input.value);updateExperiment();}));updateExperiment();}
 function evaluate(){return M[active](params);}
 function updateExperiment(){const r=evaluate();document.querySelectorAll('input[data-param]').forEach(input=>$('out-'+input.dataset.param).value=M.format(params[input.dataset.param],input.dataset.unit));let metrics,status,warn=false;if(active==='resistor'){metrics=[['电流',M.format(r.current,'A')],['功耗',M.format(r.power,'W')],['额定占比',(r.ratio*100).toFixed(1)+'%']];warn=r.ratio>1;status=warn?'超过课堂额定功率；实际器件还须检查温度降额及工作电压。':'功耗未超过课堂设定；这不等同于真实选型已通过。';}if(active==='capacitor'){metrics=[['理想容抗',M.format(r.reactance,'Ω')],['电荷量',M.format(r.charge,'C')],['储能',M.format(r.energy,'J')]];warn=params.v>16;status=warn?'超过课堂参考16 V；真实额定电压需查具体料号。':'计算使用名义容量；X7R/X5R等的有效容量还需看偏压曲线。';}if(active==='inductor'){metrics=[['理想感抗',M.format(r.reactance,'Ω')],['理想储能',M.format(r.energy,'J')],['直流铜损',M.format(r.copperLoss,'W')]];warn=r.saturated;status=warn?'超过课堂Isat=2 A；实际L可能下降，名义L模型不再可靠。':'课堂DCR=0.1 Ω、Isat=2 A；未检查Irms及真实频率/损耗条件。';}if(active==='diode'){metrics=[['模型电流',M.format(r.current,'A')],['模型功耗',M.format(r.power,'W')],['偏置方向',params.v>0?'正向':params.v<0?'反向':'零偏置']];status=params.v>0?'正向偏置：模型电流随电压连续变化，不是固定0.7 V开关。':params.v<0?'反向偏置：模型含小漏电，不模拟反向击穿。':'零偏置：简化模型中净电流为0。';} $('metrics').innerHTML=metrics.map(m=>'<div class="metric"><small>'+m[0]+'</small><strong>'+m[1]+'</strong></div>').join('');$('lab-status').textContent=status;$('lab-status').classList.toggle('warn',warn);$('state-badge').textContent=active==='resistor'?'功耗占比 '+(r.ratio*100).toFixed(0)+'%（非温度）':active==='capacitor'?'电场储能（理想模型）':active==='inductor'?(warn?'课堂饱和阈值已超过':'磁场储能（理想模型）'):(params.v>0?'正向偏置 · 约定电流A→K':params.v<0?'反向偏置 · 小漏电':'零偏置');$('state-badge').classList.toggle('danger',warn);drawPlot(r);dirty=true;}
 function drawPlot(r){let pts=[],marker,title,xlabels,ylabels;if(active==='resistor'){title='I–V：理想欧姆模型';for(let n=0;n<=60;n++)pts.push([n/60,n/60]);marker=[params.v/20,params.v/20];xlabels=['0 V','10 V','20 V'];ylabels=[M.format(20/params.r,'A'),M.format(10/params.r,'A'),'0 A'];}if(active==='capacitor'||active==='inductor'){title=(active==='capacitor'?'容抗随频率变化':'感抗随频率变化')+'（双对数坐标）';for(let n=0;n<=60;n++)pts.push([n/60,active==='capacitor'?1-n/60:n/60]);const x=(Math.log10(params.f)-1)/5;marker=[x,active==='capacitor'?1-x:x];xlabels=['10 Hz','3.16 kHz','1 MHz'];const fn=f=>active==='capacitor'?M.capacitor({...params,f}).reactance:M.inductor({...params,f}).reactance;ylabels=[M.format(fn(active==='capacitor'?10:1e6),'Ω'),M.format(fn(10**3.5),'Ω'),M.format(fn(active==='capacitor'?1e6:10),'Ω')];}if(active==='diode'){title='I–V：课堂Shockley模型（无击穿）';const max=M.diode({...params,v:.95}).current;for(let n=0;n<=80;n++){const v=-2+n/80*2.95;pts.push([n/80,Math.max(0,M.diode({...params,v}).current/max)]);}marker=[(params.v+2)/2.95,Math.max(0,r.current/max)];xlabels=['−2 V','−0.525 V','0.95 V'];ylabels=[M.format(max,'A'),M.format(max/2,'A'),'0 A'];}const x=t=>61+t*263,y=t=>126-t*89,path=pts.map((p,i)=>(i?'L':'M')+x(p[0]).toFixed(2)+' '+y(p[1]).toFixed(2)).join(' ');$('plot').innerHTML='<svg class="plot" viewBox="0 0 352 165" role="img" aria-label="'+title+'"><text x="8" y="14">'+title+'</text>'+[0,.5,1].map((t,i)=>'<path class="grid" d="M61 '+y(t)+'H324"/><text x="4" y="'+(y(t)+3)+'">'+ylabels[2-i]+'</text><text text-anchor="middle" x="'+x(t)+'" y="149">'+xlabels[i]+'</text>').join('')+'<path d="'+path+'" class="curve"/><circle class="marker" cx="'+x(marker[0])+'" cy="'+y(marker[1])+'" r="4"/></svg>';}
 function renderQuiz(){const q=courses[active].quiz;$('panel-quiz').innerHTML='<h3>一分钟检查理解</h3><p class="lead">'+q.question+'</p>'+q.options.map((o,i)=>'<button class="quiz-option" type="button" data-answer="'+i+'">'+String.fromCharCode(65+i)+' · '+o+'</button>').join('')+'<div id="quiz-feedback" aria-live="polite"></div><p class="complete">'+(answers[active]?'本节已答对，可以再做一次。':'进度仅保存在当前浏览器会话，不写入会员或业务数据库。')+'</p>';document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const correct=Number(b.dataset.answer)===q.answer;document.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('correct','incorrect'));b.classList.add(correct?'correct':'incorrect');$('quiz-feedback').className='quiz-feedback';$('quiz-feedback').textContent=(correct?'回答正确。':'再想一想。')+q.explain;if(correct){answers[active]=true;try{sessionStorage.setItem('fruition_training_answers_v1',JSON.stringify(answers));}catch(_){}courseButtons();document.querySelector('.complete').textContent='本节已答对，可以继续下一类器件。';}}));}

 // Procedural 3D meshes, perspective camera and depth sorting. All geometry
 // is local: no model downloads, CDN scripts or WebGL availability dependency.
 const canvas=$('model-canvas'),ctx=canvas.getContext('2d');let width=0,height=0,faceCache=[],fitScale=1,fitX=0,fitY=0;
 const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const d=Math.hypot(...a)||1;return mul(a,1/d);};
 function box(faces,center,size,color,id){const [x,y,z]=size.map(v=>v/2),v=[[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]].map(p=>add(p,center));for(const ix of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])faces.push({p:ix.map(i=>v[i]),color,id});}
 function tube(faces,a,b,r,color,id,sides=10,caps=true){const axis=norm(sub(b,a)),u=norm(cross(axis,Math.abs(axis[1])>.8?[1,0,0]:[0,1,0])),v=cross(axis,u),ring=p=>Array.from({length:sides},(_,i)=>add(p,add(mul(u,r*Math.cos(i/sides*2*Math.PI)),mul(v,r*Math.sin(i/sides*2*Math.PI)))));const ra=ring(a),rb=ring(b);for(let i=0;i<sides;i++){const j=(i+1)%sides;faces.push({p:[ra[i],ra[j],rb[j],rb[i]],color,id});}if(caps){faces.push({p:ra.slice().reverse(),color,id});faces.push({p:rb,color,id});}}
 function geometry(){
  const f=[],e=explosion;
  if(active==='resistor'){
   const heat=clamp(evaluate().ratio,0,1.4),film=[55+heat*85,65,80-heat*25];
   box(f,[0,-.15,0],[3,.45,1.4],[218,224,231],'substrate');box(f,[0,.12+e*.65,0],[2.6,.08,1.15],film,'film');box(f,[0,.26+e*1.5,0],[2.65,.18,1.22],[58,67,84],'cover');
   for(const x of [-1.55,1.55])box(f,[x*(1+e*.2),-.08,0],[.52,.74,1.45],[171,184,201],'terminal');
   if(e>.1){for(let i=0;i<6;i++)box(f,[-1+i*.4,.175+e*.65,(i%2?.2:-.2)],[.06,.02,.55],[214,179,88],'film');}
  }
  if(active==='capacitor'){
   const step=.11+e*.10;
   for(let i=0;i<10;i++){const y=(i-4.5)*step;box(f,[0,y,0],[2.6,.085,1.25],[217,191,136],'dielectric');box(f,[i%2?.13:-.13,y+.05,0],[2.65,.018,1.13],i%2?[139,163,192]:[184,197,213],'electrode');}
   for(const x of [-1.55,1.55])box(f,[x*(1+e*.25),0,0],[.43,1.22,1.32],[169,182,199],'terminal');
   if(e<.08)box(f,[0,0,0],[2.85,1.16,1.34],[213,183,130],'dielectric');
  }
  if(active==='inductor'){
   tube(f,[0,-.7,0],[0,.7,0],.57,[56,66,80],'core',24);
   const points=Array.from({length:91},(_,i)=>[Math.cos(i/90*Math.PI*10)*(1+e*.2),-.65+i/90*1.3,Math.sin(i/90*Math.PI*10)*(1+e*.2)]);
   for(let i=0;i<points.length-1;i++)tube(f,points[i],points[i+1],.085,[188,107,47],'winding',6,false);
   box(f,[0,-.95,0],[2.8,.35,2.5],[73,83,96],'cover');box(f,[0,.9+e*1.4,0],[2.8,.3,2.5],[80,88,100],'cover');
   if(e<.1){for(const z of [-1.16,1.16])box(f,[0,-.04,z],[2.8,1.55,.25],[80,88,100],'cover');for(const x of [-1.26,1.26])box(f,[x,-.04,0],[.28,1.55,2.4],[80,88,100],'cover');}
   for(const x of [-1.2,1.2])box(f,[x,-1.17,0],[.55,.11,1.9],[176,187,201],'terminal');
  }
  if(active==='diode'){
   const gap=clamp(.12-params.v*.12,.04,.36),lift=e*1.5;
   box(f,[-.44-gap/2,0,0],[.8,.55,.65],[205,127,92],'p');box(f,[.44+gap/2,0,0],[.8,.55,.65],[80,139,212],'n');box(f,[0,0,0],[gap,.55,.65],[216,214,204],'junction');
   // Non-overlapping shell sections keep the cathode ring visible at all angles.
   tube(f,[-1.25,lift,0],[.82,lift,0],.58,[179,120,77],'cover',24);
   tube(f,[.82,lift,0],[1.05,lift,0],.58,[41,47,60],'cover',24);
   tube(f,[1.05,lift,0],[1.25,lift,0],.58,[179,120,77],'cover',24);
   for(const side of [-1,1])tube(f,[side*1.1,0,0],[side*2.4*(1+e*.15),0,0],.075,[162,180,199],'terminal',10);
   if(e>.05){for(const side of [-1,1])tube(f,[side*.9,0,0],[side*1.2,0,0],.1,[162,180,199],'terminal');}
  }
  return f;
 }
 function rotated(p){const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),x=p[0]*cy+p[2]*sy,z=-p[0]*sy+p[2]*cy;return [x,p[1]*cx-z*sx,p[1]*sx+z*cx];}
 function fitMesh(faces){
  let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;
  const base=Math.min(width/6.5,height/4.6);
  for(const face of faces)for(const p of face.p){const q=rotated(p),s=base*9/(9-q[2]),x=q[0]*s,y=-q[1]*s;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}
  fitScale=Math.min(1,(width-40)/Math.max(1,maxX-minX),(height-56)/Math.max(1,maxY-minY));
  fitX=-(minX+maxX)/2*fitScale;fitY=-(minY+maxY)/2*fitScale;
 }
 function project(p){const q=rotated(p),s=zoom*fitScale*Math.min(width/6.5,height/4.6)*9/(9-q[2]);return [width/2+zoom*fitX+q[0]*s,height*.5-4+zoom*fitY-q[1]*s,q[2]];}
 function drawLine(points,color,line=1.5){ctx.beginPath();points.forEach((p,i)=>{const s=project(p);i?ctx.lineTo(s[0],s[1]):ctx.moveTo(s[0],s[1]);});ctx.strokeStyle=color;ctx.lineWidth=line;ctx.stroke();}
 function drawFrame(){
  if(!ctx||!width)return;
  ctx.clearRect(0,0,width,height);
  const shadow=ctx.createRadialGradient(width/2,height*.78,4,width/2,height*.78,width*.28);shadow.addColorStop(0,'rgba(35,65,104,.15)');shadow.addColorStop(1,'rgba(35,65,104,0)');ctx.fillStyle=shadow;ctx.save();ctx.translate(0,height*.43);ctx.scale(1,.45);ctx.fillRect(0,0,width,height);ctx.restore();
  const mesh=geometry();fitMesh(mesh);
  const faces=mesh.map(face=>{const q=face.p.map(rotated),screen=face.p.map(project),normal=norm(cross(sub(q[1],q[0]),sub(q[2],q[0]))),light=.62+.32*Math.abs(normal[1])+.16*Math.max(0,normal[2]);return {...face,screen,depth:q.reduce((s,p)=>s+p[2],0)/q.length,color:face.color.map(v=>Math.round(clamp(v*light,0,255)))};}).sort((a,b)=>a.depth-b.depth);
  faceCache=faces;
  for(const f of faces){ctx.beginPath();f.screen.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle='rgb('+f.color.join(',')+')';ctx.fill();ctx.strokeStyle=f.id===part?'rgba(30,96,200,.35)':'rgba(40,65,94,.08)';ctx.lineWidth=.5;ctx.stroke();}
  if(animation)drawPrinciple();drawLabels();canvas.dataset.frames=String(Number(canvas.dataset.frames||0)+1);canvas.dataset.meshFaces=String(faces.length);canvas.dataset.course=active;canvas.dataset.yaw=yaw.toFixed(3);canvas.dataset.zoom=zoom.toFixed(3);dirty=false;
 }
 function dot(p,color,r=3){const s=project(p);ctx.beginPath();ctx.arc(s[0],s[1],r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
 function drawPrinciple(){
  if(active==='resistor'&&params.v>0){for(let i=0;i<6;i++)dot([-1.8+((time*.8+i/6)%1)*3.6,.5+explosion*1.5,.06],'#3478ee');}
  if(active==='capacitor'&&params.v>0){
   if(explosion<.15){dot([-1.8,0,0],'#d97849',4);dot([1.8,0,0],'#2979d6',4);}
   else {const step=.11+explosion*.10;for(let i=0;i<10;i++){const y=(i-4.5)*step+.05;for(const x of [-.65,.65])dot([x,y,.60],i%2?'#2979d6':'#d97849',3);if(i<9){const from=i%2?y+step:y,to=i%2?y:y+step;drawLine([[0,from,.62],[0,to,.62]],'rgba(44,110,212,.65)',1.2);const mid=(from+to)/2,sign=to>from?1:-1;drawLine([[-.05,mid-sign*.05,.62],[0,mid,.62],[.05,mid-sign*.05,.62]],'#367de0',1);}}}
  }
  if(active==='inductor'&&params.i>0){for(const side of [-1,1]){const points=Array.from({length:40},(_,i)=>{const a=i/39*2*Math.PI;return [side*(.7+.5*Math.sin(a)),1.45*Math.cos(a),0];});drawLine(points,evaluate().saturated?'#c56463':'#568ece',1.3);dot(points[Math.floor((time*.15)%1*39)],'#397de0',3);}}
  if(active==='diode'&&params.v>0&&evaluate().current>1e-6){for(let i=0;i<5;i++)dot([-2+((time*.6+i/5)%1)*4,-.75,0],'#337aec');drawLine([[-1.4,-.75,0],[1.4,-.75,0]],'rgba(38,104,210,.35)',1);}
 }
 function drawLabels(){let labels=active==='resistor'?[['substrate',[-.5,-.45,.7]],['film',[.4,.18+explosion*.65,.4]],['cover',[0,.36+explosion*1.5,0]],['terminal',[1.75,0,0]]]:active==='capacitor'?[['dielectric',[.6,.45+explosion*.4,.65]],['electrode',[-.4,.27+explosion*.25,.65]],['terminal',[1.75,0,0]]]:active==='inductor'?[['core',[0,.55,.58]],['winding',[1,.15,0]],['cover',[0,1.08+explosion*1.4,0]],['terminal',[1.2,-1.22,0]]]:[['p',[-.65,0,.4]],['junction',[0,.25,.4]],['n',[.65,0,.4]],['cover',[0,.65+explosion*1.5,0]],['terminal',[2.2,0,0]]];for(let i=0;i<labels.length;i++){const [id,p]=labels[i],s=project(p);if(explosion<.15&&['film','p','junction','n','core','winding','electrode'].includes(id))continue;ctx.beginPath();ctx.arc(s[0],s[1],10,0,2*Math.PI);ctx.fillStyle=id===part?'#1555e8':'#ffffffed';ctx.fill();ctx.strokeStyle='#7b9fce';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=id===part?'white':'#234d83';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='11px "Segoe UI",sans-serif';ctx.fillText(String(i+1),s[0],s[1]);}}
 function contains(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
 function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true;}
 const pointers=new Map();let start=null,moved=false,lastPinch=0;
 canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY};moved=false;auto=false;$('rotate').setAttribute('aria-pressed','false');});
 canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;const current={x:e.clientX,y:e.clientY};pointers.set(e.pointerId,current);if(pointers.size===2){const [a,b]=[...pointers.values()],dist=Math.hypot(a.x-b.x,a.y-b.y);if(lastPinch)zoom=clamp(zoom*dist/lastPinch,.55,1.65);lastPinch=dist;moved=true;}else{yaw+=(current.x-old.x)*.009;pitch=clamp(pitch+(current.y-old.y)*.008,-1.3,1.3);if(start&&Math.hypot(current.x-start.x,current.y-start.y)>5)moved=true;}dirty=true;});
 const release=e=>{pointers.delete(e.pointerId);lastPinch=0;if(!moved&&start&&e.type==='pointerup'){const rect=canvas.getBoundingClientRect(),point=[e.clientX-rect.left,e.clientY-rect.top];const face=faceCache.slice().reverse().find(f=>contains(point,f.screen));if(face)selectPart(face.id);}start=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*Math.exp(-e.deltaY*.001),.55,1.65);dirty=true;},{passive:false});canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch=clamp(pitch-.1,-1.3,1.3);if(e.key==='ArrowDown')pitch=clamp(pitch+.1,-1.3,1.3);if(e.key==='+'||e.key==='=')zoom=clamp(zoom*1.1,.55,1.65);if(e.key==='-')zoom=clamp(zoom/1.1,.55,1.65);if(e.key==='0'){yaw=.55;pitch=-.4;zoom=1;}dirty=true;});
 $('explode').addEventListener('input',e=>{explosion=Number(e.target.value);$('explode-value').value=Math.round(explosion*100)+'%';dirty=true;});$('rotate').addEventListener('click',()=>{auto=!auto;$('rotate').setAttribute('aria-pressed',String(auto));dirty=true;});$('animate').setAttribute('aria-pressed',String(animation));$('animate').addEventListener('click',()=>{animation=!animation;$('animate').setAttribute('aria-pressed',String(animation));dirty=true;});$('reset-view').addEventListener('click',()=>{yaw=.55;pitch=-.4;zoom=1;auto=false;$('rotate').setAttribute('aria-pressed','false');dirty=true;});
 let visible=true,last=0;new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)dirty=true;}).observe(canvas);new ResizeObserver(resize).observe(canvas);function loop(now){if(visible&&now-last>32){const dt=Math.min((now-last)/1000,.05);last=now;if(animation)time+=dt;if(auto){yaw+=dt*.25;dirty=true;}if(dirty||animation)drawFrame();}requestAnimationFrame(loop);}
 renderCourse();resize();requestAnimationFrame(loop);if(!ctx){canvas.insertAdjacentHTML('afterend','<p class="fallback">当前浏览器无法绘制模型，请使用较新版本浏览器。规格、原理和参数计算仍可使用。</p>');}
 window.TrainingLesson=Object.freeze({current:()=>({course:active,params:{...params},result:evaluate(),explosion,tab,part}),calculate:M,bounds:()=>{const points=faceCache.flatMap(f=>f.screen);return {left:Math.min(...points.map(p=>p[0])),right:Math.max(...points.map(p=>p[0])),top:Math.min(...points.map(p=>p[1])),bottom:Math.max(...points.map(p=>p[1])),width,height};}});
})();
