(function(){
 'use strict';
 const $=id=>document.getElementById(id),M=window.TrainingCircuitMath,format=window.TrainingMath.format;
 const content={
  resistor:{title:'电阻在PCB上：串在LED前面，限制电流',steps:['还没接通','接通，LED亮起','调整阻值'],head:['开关断开，电流走不通','电流经过电阻，再经过LED','改变R1，观察电流和亮度'],story:['先找完整回路：电源正端 → 开关 → R1 → LED → 地线 → 电源负端。开关断开时没有持续电流。','电阻与LED串联，同一支路电流相同。R1承担电源与LED之间的部分电压差，把电流限制在一个水平。','选220 Ω或1 kΩ进行对比。相同电源和课堂LED压降下，阻值增大，电流减小；灯的亮度只作定性示意。'],takeaway:'不是“挡住电流”，而是通过阻值控制这条支路的电流。',assumptions:'课堂：电源5 V，LED导通压降暂取2 V，R=220 Ω或1 kΩ。I=(5−2)/R，亮度为定性示意；真实LED压降、电流额定值和热条件须查规格书。本电路参数独立于下方器件实验。',sources:[['欧姆模型与电阻额定条件 · Vishay','https://www.vishay.com/docs/20035/dcrcwe3.pdf']]},
  capacitor:{title:'电容在PCB上：并在芯片电源旁，短时间补电',steps:['平稳供电','芯片突然多用电','负载回落，电容回充'],head:['电容已充电，芯片正常用电','芯片要的电流突然增加，电容先补一部分','电源给芯片供电，也给电容补回能量'],story:['C1并联在芯片的电源脚和地之间，并不是串在供电线上。稳态时，理想电容支路电流为零。','蓝色是电源送来的电流，橙色是电容放出的电流。刚发生变化时电容电压不突变，随后会下降。可移除C1对比。','负载回到较小电流后，电源的一部分电流流入电容。橙色箭头换向，表示回充；电容不能无限供电。'],takeaway:'电容像靠近芯片的“小储备”，在短暂变化时补电，之后还要回充。',assumptions:'课堂供电3.3 V，供电路径简化为1 Ω，C=10 µF；负载5 mA→100 mA→5 mA，每个变化阶段为5RC=50 µs。满足C·dV/dt=(Vs−V)/Rs−I负载。此RC模型不模拟真实PCB走线电感、ESR/ESL、DC偏压或芯片内部行为。蓝色为电源支路，橙色为电容支路；箭头不穿过绝缘介质。实际去耦应按芯片要求、阻抗及布局核对。',sources:[['TI · 去耦电容的作用与PCB连接','https://e2e.ti.com/blogs_/archives/b/precisionhub/posts/the-decoupling-capacitor-is-it-really-necessary']]},
  inductor:{title:'电感在PCB上：电流缓慢变化，断开后沿续流回路流动',steps:['开关断开','接通，电流逐渐上升','断开，电流逐渐下降'],head:['还没有储能，电流为零','电源供能，电感中的电流逐渐增加','电源断开，但电感电流不立即消失'],story:['先认位置：S1后面是电感L1和负载R1，D1提供另一条回流通路。此时没有初始储能。','电流从电源经S1、L1、R1回到负端。电感电流不能瞬间跃变，磁场能量随电流增加；此时D1反向截止。','橙色续流回路：L1 → R1 → 地线 → D1 → L1。电流仍沿原方向经过L1，储能逐渐消耗，电流慢慢趋近零。'],takeaway:'电感反对电流突然变化；断开供电后，电流仍需要闭合的续流路径。',assumptions:'课堂为带理想续流二极管的RL电路，不是完整Buck降压电源：Vs=5 V、L=1 mH、R=10 Ω，时间常数L/R=0.1 ms；每阶段展示5个时间常数。通电I=Vs/R·(1−exp(−tR/L))，断电I=I初始·exp(−tR/L)。忽略二极管压降、磁饱和及寄生参数；未展示“拆掉续流二极管”的高压冲击。',sources:[['Analog Devices · 开关电路的储能与续流','https://www.analog.com/media/en/training-seminars/design-handbooks/power-thermal-mgmt-sect3.pdf']]},
  diode:{title:'二极管在PCB上：串在电源入口，阻止接反电流',steps:['没有供电','电源正常接入','电源接反'],head:['先认阳极A和阴极K','正常接电时正向导通，负载得到电压','接反时反向截止，负载没有得到反向供电'],story:['D1串在电源入口与负载之间，A朝输入端，K朝负载端。这是串联防反接示例，不代表所有二极管应用。','电流从输入端经过D1和负载回到电源。负载电压比输入低一些，因为真实二极管会有正向压降。','二极管方向没变，但输入变成−5 V。它处于反向偏置，课堂模型中支路电流为零，负载电压为零。'],takeaway:'正常方向能供电，电源接反时阻断；但正向导通也会有压降和损耗。',assumptions:'课堂采用串联二极管、1 kΩ负载和+5/−5 V输入。正向压降0.7 V仅为本例定压降假设，不是固定导通门槛；反向电流按理想零处理。真实器件有漏电、反向耐压和电流限制，且可能击穿；本例不保证任意器件都能防反接。',sources:[['TI · 串联二极管防反接与损耗','https://www.ti.com/video/5401252710001']]}
 };
 let course=window.TrainingLesson.current().course,step=0,u=0,view='pcb',playing=false,visible=true,last=0,elapsed=0,options={r:1000,cap:true},flowNodes=[];
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const evaluate=()=>M.evaluate(course,step,u,options);
 function stop(){playing=false;$('circuit-play').setAttribute('aria-pressed','false');$('circuit-play').textContent='播放分步演示';}
 function source(label){return '<path class="wire" d="M80 125V95M80 185V220"/><circle class="device source-device" cx="80" cy="155" r="30"/><text x="80" y="147" class="polarity">+</text><text x="80" y="174" class="polarity">−</text><text x="80" y="57" text-anchor="middle">'+label+'</text><text x="80" y="252" text-anchor="middle">电源负端 / GND</text>';}
 function wire(d){return '<path class="wire" d="'+d+'"/>';}
 function resistor(x,y,vertical=false){return '<g transform="translate('+x+' '+y+')'+(vertical?' rotate(90)':'')+'"><rect class="device resistor-device" x="-35" y="-13" width="70" height="26" rx="3"/><path class="schematic-mark" d="M-25 0H25"/></g>';}
 function diode(x,y,angle=0,id=''){return '<g transform="translate('+x+' '+y+') rotate('+angle+')"><rect class="pcb-package" x="-20" y="-15" width="40" height="30" rx="3"/><path class="symbol" d="M-20 0H-14M-14 -13L12 0L-14 13Z M14 -15V15M14 0H20"/></g>'+ (id?'<text x="'+(x+33)+'" y="'+(y+5)+'">'+id+'</text>':'');}
 function switchShape(){return '<circle class="switch-pad" cx="140" cy="95" r="4"/><circle class="switch-pad" cx="180" cy="95" r="4"/><path id="circuit-switch" class="switch-blade" d="M140 95L178 75"/><text x="160" y="57" text-anchor="middle">S1 开关</text>';}
 function flow(id,d,color='source'){return '<path id="flow-'+id+'" class="flow-track '+color+'" d="'+d+'"/><path id="arrow-'+id+'" class="current-arrow '+color+'" d="M-7 -5L7 0L-7 5Z"/>';}
 function buildDrawing(){
  let shapes='',flows='';
  if(course==='resistor'){
   shapes=source('电源 5 V')+wire('M80 95H140M180 95H235M305 95H450V135M450 175V220H80')+switchShape()+resistor(270,95)+'<text x="270" y="57" text-anchor="middle">R1 限流电阻</text><circle id="circuit-led-glow" cx="450" cy="155" r="34"/><g id="circuit-led">'+diode(450,155,90)+'</g><text x="490" y="160">LED</text><text id="circuit-r-value" x="270" y="138" text-anchor="middle"></text><text x="430" y="120">A</text><text x="430" y="195">K</text>';
   flows=flow('main','M80 125V95H450V220H80V185');
  }else if(course==='capacitor'){
   shapes=source('电源 3.3 V')+wire('M80 95H165M235 95H450V125M450 195V220H80M310 95V150M310 170V220')+resistor(200,95)+'<text x="200" y="57" text-anchor="middle">供电路径 Rs=1 Ω</text><circle class="junction" cx="310" cy="95" r="4"/><circle class="junction" cx="310" cy="220" r="4"/><g id="circuit-cap-body"><rect class="pcb-package" x="291" y="145" width="38" height="30" rx="3"/><path class="symbol" d="M286 150H334M286 170H334"/></g><text x="270" y="162" text-anchor="end">C1</text><text x="270" y="184" text-anchor="end">10 µF</text><rect class="device ic-device" x="409" y="125" width="82" height="70" rx="5"/><text x="450" y="154" text-anchor="middle">芯片IC</text><text id="circuit-load-label" x="450" y="178" text-anchor="middle"></text><text x="478" y="115">VCC</text><text x="478" y="216">GND</text>';
   flows=flow('source','M80 125V95H310')+flow('load','M310 95H450V220H310')+flow('return','M310 220H80V185')+flow('cap-up','M310 95V150','energy')+flow('cap-down','M310 170V220','energy');
  }else if(course==='inductor'){
   shapes=source('电源 5 V')+wire('M80 95H140M180 95H265M355 95H450V120M450 190V220H80M230 95V135M230 175V220')+switchShape()+'<path class="coil symbol" d="M265 95Q265 66 285 95Q285 66 305 95Q305 66 325 95Q325 66 345 95H355"/><rect class="pcb-package" x="264" y="76" width="90" height="38" rx="5"/><path class="pcb-coil" d="M275 95Q275 80 290 95Q290 80 305 95Q305 80 320 95Q320 80 335 95"/><text x="310" y="57" text-anchor="middle">L1 电感 1 mH</text>'+resistor(450,155,true)+'<text x="480" y="151">负载R1</text><text x="480" y="176">10 Ω</text>'+diode(230,155,-90,'D1')+'<text x="210" y="129">K</text><text x="210" y="193">A</text><circle class="junction" cx="230" cy="95" r="4"/><circle class="junction" cx="230" cy="220" r="4"/>';
   flows=flow('supply','M80 125V95H450V220H80V185')+flow('freewheel','M230 220V95H450V220H230','energy');
  }else{
   shapes=source('输入端')+wire('M80 95H250M290 95H450V120M450 190V220H80')+diode(270,95)+resistor(450,155,true)+'<text x="270" y="57" text-anchor="middle">D1 串联防反接</text><text x="240" y="136">A</text><text x="293" y="136">K</text><text id="circuit-input-value" x="80" y="100" text-anchor="middle"></text><text x="477" y="147">负载</text><text x="477" y="176">1 kΩ</text><text id="circuit-output-value" x="400" y="67"></text>';
   flows=flow('main','M80 125V95H450V220H80V185');
  }
  $('circuit-drawing').innerHTML='<svg id="circuit-svg" class="'+view+'" viewBox="0 0 560 275" role="img" aria-label="'+content[course].title+'"><rect class="board" x="12" y="15" width="536" height="250" rx="12"/>'+shapes+'<g class="current-paths">'+flows+'</g></svg>';
  flowNodes=[...document.querySelectorAll('#circuit-svg .flow-track')].map(path=>({id:path.id.slice(5),path,arrow:$('arrow-'+path.id.slice(5)),length:path.getTotalLength()}));
 }
 function stateFlows(r){if(course==='resistor'||course==='diode')return {main:r.i};if(course==='capacitor')return {source:r.source,load:r.load,return:r.source,'cap-up':r.icap,'cap-down':r.icap};return {supply:r.closed?r.i:0,freewheel:r.freewheel?r.i:0};}
 function renderState(clock=0){
  const r=evaluate(),flows=stateFlows(r);
  for(const f of flowNodes){const current=flows[f.id]||0,on=Math.abs(current)>1e-7,sign=current<0?-1:1;f.path.style.opacity=on?'1':'0';f.arrow.style.opacity=on?'1':'0';f.path.dataset.current=String(current);const distance=playing?(clock*.07*sign%f.length+f.length)%f.length:f.length*.58;const p=f.path.getPointAtLength(distance),q=f.path.getPointAtLength(Math.min(f.length,distance+1));f.arrow.setAttribute('transform','translate('+p.x+' '+p.y+') rotate('+(Math.atan2(q.y-p.y,q.x-p.x)*180/Math.PI+(sign<0?180:0))+')');}
  if(course==='resistor'){ $('circuit-r-value').textContent=r.r+' Ω';$('circuit-led-glow').style.opacity=String(r.brightness*.75);$('circuit-led').classList.toggle('lit',r.i>0);$('circuit-switch').setAttribute('d',r.closed?'M140 95H180':'M140 95L178 75');}
  if(course==='capacitor'){ $('circuit-load-label').textContent=format(r.load,'A');$('circuit-cap-body').style.opacity=r.present?'1':'.2';}
  if(course==='inductor')$('circuit-switch').setAttribute('d',r.closed?'M140 95H180':'M140 95L178 75');
  if(course==='diode'){ $('circuit-input-value').textContent=(r.input>0?'+':'')+r.input+' V';$('circuit-output-value').textContent='负载 '+r.output.toFixed(1)+' V';const signs=document.querySelectorAll('#circuit-svg .polarity');signs[0].textContent=r.reverse?'−':'+';signs[1].textContent=r.reverse?'+':'−';}
  const metrics=course==='resistor'?[['支路电流',format(r.i,'A')],['电阻功耗',format(r.p,'W')]]:course==='capacitor'?[['芯片供电',r.v.toFixed(3)+' V'],[r.icap<0?'电容补电':'电容回充',format(Math.abs(r.icap),'A')]]:course==='inductor'?[['电感电流',format(r.i,'A')],['磁场储能',format(r.energy,'J')]]:[['负载电压',r.output.toFixed(1)+' V'],['支路电流',format(r.i,'A')]];
  $('circuit-metrics').replaceChildren(...metrics.map(([label,value])=>{const n=node('div');n.append(node('span',label),node('strong',value));return n;}));
  $('circuit-time').textContent=(playing?'慢放演示中 · ':step===2&&u===1?'演示结束 · ':'手动查看 · ')+(course==='capacitor'||course==='inductor'?'本阶段真实时间 '+format(r.t,'s'):'参数为课堂示例');
  $('circuit-card').dataset.course=course;$('circuit-card').dataset.step=String(step);$('circuit-card').dataset.progress=u.toFixed(3);
 }
 function selectStep(next,progress=0){stop();step=next;u=progress;elapsed=u*4500;const c=content[course];$('circuit-stage').textContent='第 '+(step+1)+' / 3 步';$('circuit-headline').textContent=c.head[step];$('circuit-story').textContent=c.story[step];$('circuit-status').textContent=c.head[step];document.querySelectorAll('[data-circuit-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.circuitStep)===step)));$('circuit-next').disabled=step===2;renderState();}
 function renderCourse(){stop();step=0;u=0;elapsed=0;options={r:1000,cap:true};const c=content[course];$('circuit-title').textContent=c.title;$('circuit-takeaway').textContent=c.takeaway;$('circuit-assumptions').textContent=c.assumptions;$('circuit-sources').replaceChildren(...c.sources.map(([label,url])=>{const a=node('a',label+' ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}));$('circuit-steps').replaceChildren(...c.steps.map((title,i)=>{const b=node('button',(i+1)+' · '+title);b.type='button';b.dataset.circuitStep=String(i);b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>selectStep(i));return b;}));$('circuit-options').replaceChildren();if(course==='resistor'){const label=node('label','对比阻值 '),select=node('select');select.id='circuit-resistance';select.setAttribute('aria-label','PCB限流电阻阻值');for(const r of [220,1000]){const o=node('option',r+' Ω');o.value=String(r);select.append(o);}select.value='1000';select.addEventListener('change',()=>{options.r=Number(select.value);selectStep(2);});label.append(select);$('circuit-options').append(label);}if(course==='capacitor'){const b=node('button','对比：移除C1');b.id='circuit-remove-cap';b.type='button';b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{stop();options.cap=!options.cap;b.setAttribute('aria-pressed',String(!options.cap));b.textContent=options.cap?'对比：移除C1':'恢复C1';if(step===0)selectStep(1);else renderState();});$('circuit-options').append(b);}buildDrawing();selectStep(0);}
 function setView(next){view=next;$('circuit-pcb').setAttribute('aria-pressed',String(view==='pcb'));$('circuit-schematic').setAttribute('aria-pressed',String(view==='schematic'));buildDrawing();renderState();}
 $('circuit-pcb').addEventListener('click',()=>setView('pcb'));$('circuit-schematic').addEventListener('click',()=>setView('schematic'));
 $('circuit-next').addEventListener('click',()=>selectStep(Math.min(2,step+1)));$('circuit-reset').addEventListener('click',()=>{renderCourse();});
 $('circuit-play').addEventListener('click',()=>{if(playing){stop();renderState();return;}if(step===2&&u===1)selectStep(0);playing=true;last=0;$('circuit-play').setAttribute('aria-pressed','true');$('circuit-play').textContent='暂停演示';});
 window.addEventListener('training-course-change',e=>{course=e.detail.course;renderCourse();});
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;last=0;}).observe($('circuit-card'));
 document.addEventListener('visibilitychange',()=>{last=0;});
 let painted=0;function loop(now){if(playing&&visible&&!document.hidden){if(last)elapsed+=Math.min(100,now-last);last=now;const duration=step===0?2000:4500;u=Math.min(1,elapsed/duration);if(now-painted>50){painted=now;renderState(now);}if(u===1){if(step<2){const next=step+1;selectStep(next);playing=true;$('circuit-play').setAttribute('aria-pressed','true');$('circuit-play').textContent='暂停演示';last=now;}else{stop();renderState();$('circuit-status').textContent='演示结束，可以逐步复看。';}}}else last=0;requestAnimationFrame(loop);}
 renderCourse();requestAnimationFrame(loop);
 window.TrainingCircuit=Object.freeze({current:()=>({course,step,u,view,playing,options:{...options},result:evaluate()}),selectStep:(s,p=0)=>selectStep(s,p)});
})();
